### ISSUE TITLE
Grav Trap bug

### ISSUE THREAD

**Issue by Nikos2k** [SubnauticaNitrox/Nitrox#1426] opened 2021-02-21 23:03 UTC
My friend became a grav trap after throwing away one, no it fixed after 2 restart's but it was cumbersome![unknown-1.png](https://user-images.githubusercontent.com/59316298/108641743-4d473100-74a1-11eb-9ea9-94d61a735bd1.png)![unknown.png](https://user-images.githubusercontent.com/59316298/108641756-5801c600-74a1-11eb-9c0c-b6b63c5da0b4.png)

**Comment by Gangsteri** [comment] 2021-03-08 22:03
Dude thats not a bug its more of like a "feature".

**Comment by Nikos2k** [comment] 2021-03-25 09:40
> Dude thats not a bug its more of like a "feature".

Unless the robo-spiders from aurora are attacking you or leeches or even stalkers

**Comment by Measurity** [comment] 2021-11-17 09:10
Closing as there are no reproducible steps in this issue so we can't fix it.

**Closed by Measurity** 2021-11-17 09:10 UTC
Labels: Type: bug
