### ISSUE TITLE
Leviathan Desync

### ISSUE THREAD

**Issue by Mrjman9991** [SubnauticaNitrox/Nitrox#1588] opened 2021-09-05 18:10 UTC
### Version
1.5.0.1
### Bug
This happened with the reaper leviathan spawn right in front of the ship in the crash zone, and we have yet to test other reaper leviathan spawns due to fear this issue might repeat itself. When playing with a friend, we encountered a reaper leviathan that was only visible to each one of us individually at a time, almost as if there were 'two' there - one I could see that was frozen/bugged out in the middle of the water, and one that he could see that was behaving normally. Neither one of 'our' leviathans could damage the other player, and were completely invisible to the other. My seamoth was getting grabbed and screamed at on his screen, but took no damage, did not get moved an inch, and could not see a thing. After I killed the leviathan on my screen because it was stuck and unmoving, his did not disappear with the death of mine and still tries to attack him whenever he goes near it, despite the fact that it is not there for me and I can swim around as though it didn't exist. For some reason, though, it still sees me as a target and will follow my seamoth and try to kill me anyway, usually resulting in the death of my friend because it deals no damage to me and on my screen might as well not even exist. 

### Expected
Reaper leviathan is only visible to one individual player, making it seem as though there are 'two'. Most likely caused by desync, as there are multiple other smaller creatures that exhibit the same bug (ex. bone sharks, warpers, stalkers) and seem to be visible only to one player.
### Steps to reproduce
Take two players to reaper leviathan spawn in front of crash zone.

**Comment by Jannify** [comment] 2021-09-05 18:25
Duplicate of #113 and #1153

**Closed by Jannify** 2021-09-05 18:25 UTC
