### ISSUE TITLE
Vehicles in the Moonpool desync when leaving

### ISSUE THREAD

**Issue by nomelkettle** [SubnauticaNitrox/Nitrox#1666] opened 2021-12-08 07:16 UTC
### Version
Version 1.5.0.1

### Bug
When a player leaves a moonpool with a vehicle, they will be able to move away no problem, but other players will still see them in the moonpool. The audio of the vehicle can be heard in the correct locations, and other players see them in the correct location once they have exited the vehicle.

### Expected
All other players will see a vehicle in the moonpool even when another player has driven it away. It will appear slightly darker with a green tint, and the driver can be seen within moving the steering wheel. 

As a temporary fix, removing the seamoth from the moonpool, slightly breaking the moonpool, repairing it and getting back in the seamoth will update its location for other players.

![unknown](https://user-images.githubusercontent.com/95739543/145165048-78013151-8fac-4008-8c5b-b27e0471f9c9.png)
Perspective of player 1 ^

![Screenshot_2](https://user-images.githubusercontent.com/95739543/145165079-30ffadce-ade1-442e-b73c-4c29f5149322.png)
Perspective of player 2 ^

### Steps to reproduce
Have one player get into a seamoth while it is in a moonpool. They will be able to drive around with no issue.
Have another player observe the moonpool, and they should still see the seamoth and player sitting there.

**Comment by Measurity** [comment] 2021-12-09 13:29
Duplicate of #1398

**Closed by Measurity** 2021-12-09 13:29 UTC
