### ISSUE TITLE
World Serilization error

### ISSUE THREAD

**Issue by Cha14ka** [SubnauticaNitrox/Nitrox#837] opened 2019-09-22 19:58 UTC
![изображение](https://user-images.githubusercontent.com/16352397/65393676-66b7eb00-dd8c-11e9-8ef0-4c5e39531d76.png)
Every time then I save and load world - he ded

**Comment by Coding-Hen** [comment] 2019-09-23 22:06
This is a duplicate #832

**Comment by Coding-Hen** [comment] 2020-03-19 23:04
Duplicate of #832

**Closed** 2020-04-08 20:33 UTC
