### ISSUE TITLE
Overall Building Bugs

### ISSUE THREAD

**Issue by ScriptedAnar** [SubnauticaNitrox/Nitrox#691] opened 2019-01-30 20:08 UTC
There are many building bugs which make the game really unplayable 

- [ ] 1.Reinforcements arent Sync with other players

- [ ] 2.Many things that you build when you rejoin they arent full constructed example moonpolls some Multiporpuse rooms Reinforcements and etc

- [ ] 3.Fabricators that are in bases when you rejoin they are unpowered and you must reconstruct them every time you join the server (That may happens with Modification Stations too)

- [ ] 4.Every time you join the game the power is always 0 

- [ ] 5.Placing posters in a wall it isnt visible to other players 

- [ ] 6.Bio/nuclear reactors (known bug) 

- [ ] 7.Solar Panels are "flying" from the base #668 

- [ ] 8.Upgrade Console and water filtration are super buggy and position is bugged when you rejoin #688 

Probably there are more these are what i have found for now.

**Comment by hanawovino** [comment] 2019-02-01 01:11
I can confirm these issues, especially multipurpose rooms. If you rejoin the server, they are back at 97% or something. Items (like the water filtration) you placed inside of them are now glitched (show up as red) and can't be destructed or rebuilt anymore.

**Comment by Tinkertee** [comment] 2019-02-19 01:39
I have the same issue on my end. I restarted the server and Subnautica and it's all screwed up for me aswell. ( Happened while my husband was out resource gathering and I was building - He was bugged and couldnt see most of the buildings, upon reset/restart it was buggy for me aswell )

**Comment by FlameCraft1234** [comment] 2019-02-22 00:33
This is very true it happens to me.

**Comment by acidscorch** [comment] 2019-04-10 07:33
Hello NitroxPower, 

are these all building related known issues? Could you please check again all issues and reference/concentrate them here? I would like to have this issue as single work-list.

For the following points i have fixes ready, but would like to finish first all issues before creating a PR.
Fixes:
- BaseLayout save/load (structures, inferiour, furniture saved/reloaded at the correct location)
- BuiltOrder correct save and ordering logic for InitialSync after reconnect: base-main-structures (e.g. corridors, foundations, rooms) before base-attachments (e.g. reinforcements, windows) before interiour before furniture  (fixes flying solar-panels, because they are now placed after the grounding base-structure)
[on my todo list: relation-list for reinforcements, to place them directly after the related base-main-structure is placed, to avoid structure-leaks at initial sync e.g. when moonpool is placed before reinforcements]
- Deconstruction is now synced and saved for nearly all objects [on my todo list: filtermachine, reactors, waterpark)
- VerticalConnectors saved/loaded (SN returns wrong techtype after construct begin which needs to be switched to correct one)
- Correct handling of Ladders/Water Tank (they create 2 deconstructables at finish, so the player can deconstruct them from the lower or the upper floor, both deconstructables are related now to the original guid)
- Correct handling of Hatches that build to a room (these create a mini corridor which doesn't instantiate a deconstructable, instead of creating a FaceDeconstructable)
- guid transfer at RebuildGeometry now correct (location and name was not enough for referencing, because attachments and interiour share the same location, but are connected to different faces, guids are now reapllied to the correct original object)

On my todo list: 
- interiour interactable objects (reactors, watertank, filtermachine) have usage and deconstructing issues
- because of no energy sync/save, i would initiate energy-objects with 50% energy as quick win solution (to discuss and may be remove later, when energy sync is implemented)
- initiating of fabricator after reconnect

Am i missing something else?

**Comment by NitroxPower** [comment] 2019-04-10 09:57
When i found those bugs i played without using any commands untill a bug happened with infinity loading but its fixed now. Here are the remaining stuff:

- The upgrade console is a serious problem cause not only it has position problems but it doest sync correctly the upgrade modules, i contact Asimpson87 which that time he was fixing vehicle problems.
![image](https://user-images.githubusercontent.com/46358553/55869159-a26c4900-5b8e-11e9-80e5-045c603fa2f9.png)

- And the hardest part are the nuclear/bio reactor cause Sunrunner and other people had attempted really hard to fix these even remaking the hole code and it never worked.

- Also the posters Sync.

Everything else is probably fixed from what i saw in your fixes

The Version i used was the 1.0.3.1 but since i was active on github i dint saw anybody fixing anything from building issues so they still the same.

**Comment by acidscorch** [comment] 2019-04-10 10:57
Okay, thanks for the summary. I will update my former comment when i have made progress on the points. 

You are right. The cyclops building is a whole thing for it's own, because position and relation infos must be calculated on this "movable base object". Lets first get the stationary objects finished and move to this later.

**Comment by acidscorch** [comment] 2019-04-11 14:02
All stationary constructing and deconstructing should be fixed now. 

Could you please beta test?

Server: 
acidscorch.ddns.net

Client:
https://www.dropbox.com/s/jtq5zwbkewtkg4b/AcidScorch%20-%20Beta%20-%20Building3.zip?dl=0

Attention:
- This is a TEST-ONLY Version and branched from an earlier state of nitrox, so the latest changes of master are not included 
- Download-Package includes only Client-Binarys, no new updated Server
- Client !must only! be used with my server, because there are new server objects. Using this client-package with other servers could crash the servers or corrupt the save-files. 
- Console is active !BUT don't use instantbuilder, because nitrox needs the events for begin, amount and end of construction/deconstruction

**Comment by NitroxPower** [comment] 2019-04-11 16:53
@acidscorch you sended me a folder having bunch of things should i replace these files with the current version of Alpha-1.1.0.1? And for server ip i should put acidscorch.ddns.net?

**Comment by NitroxPower** [comment] 2019-04-11 16:53
@acidscorch you sended me a folder having bunch of things should i replace these files with the current version of Alpha-1.1.0.1? And for server ip i should put acidscorch.ddns.net?

**Comment by NitroxPower** [comment] 2019-04-11 16:53
@acidscorch you sended me a folder having bunch of things should i replace these files with the current version of Alpha-1.1.0.1? And for server ip i should put acidscorch.ddns.net?

**Comment by NitroxPower** [comment] 2019-04-11 16:53
@acidscorch you sended me a folder having bunch of things should i replace these files with the current version of Alpha-1.1.0.1? And for server ip i should put acidscorch.ddns.net?

**Comment by NitroxPower** [comment] 2019-04-11 16:54
@acidscorch you sended me a folder having bunch of things should i replace these files with the current version of Alpha-1.1.0.1? And for server ip i should put acidscorch.ddns.net?

**Comment by acidscorch** [comment] 2019-04-11 17:55
Yes, that's because i've created my branch quite a while ago and there have been many changes on master lately which would take me more then a week to rebase without losing changes.

You said, at rejoining you had infinite loading bug? could you send a link to the output.log from Subnautica folder or post the Error if there is one in this log?

**Comment by NitroxPower** [comment] 2019-04-11 19:19
Here: [output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3070232/output_log.txt)

**Comment by acidscorch** [comment] 2019-04-11 19:30
Oh, i see you are using the epic version. Could you grab the discord-rpc.dll from the lib folder and copy it over to C:/Program Files/Epic Games/Subnautica/Subnautica_Data/Mono/

That's what the error says:
Fallback handler could not load library C:/Program Files/Epic Games/Subnautica/Subnautica_Data/Mono/discord-rpc

I think this is already fixed in the latest version on master here.

**Comment by NitroxPower** [comment] 2019-04-11 19:36
I placed the dll to the right location now when i tried to join your server(it was doing this even i dint placed the dll) it is saying that the name i used before already in use 
![Capture](https://user-images.githubusercontent.com/46358553/55987376-1cddbb80-5caa-11e9-9278-16614d5fc980.PNG)

I even tryed putting another name and when i press join then nothing happens

**Comment by acidscorch** [comment] 2019-04-11 19:38
That is a known behavior, when the last disconnect from the server wasn't clean. Then the formerly player session is still open. I've restarted the server, please try again.

**Comment by NitroxPower** [comment] 2019-04-11 19:44
this doest look right does it? 
![image](https://user-images.githubusercontent.com/46358553/55987933-4814da80-5cab-11e9-85f7-612dfbdb429a.png)

Also In-Game chat is broken

**Comment by NitroxPower** [comment] 2019-04-11 19:53
i tryed to rejoin to check if base is ok and it happened again: [output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3070339/output_log.txt)

**Comment by acidscorch** [comment] 2019-04-11 20:01
Oh, these are other errors. Checking them will take few minutes.

**Comment by acidscorch** [comment] 2019-04-11 20:01
Ingame chat is off cause of active console

**Comment by acidscorch** [comment] 2019-04-11 20:21
Ok, i got the error localised. Face-Mapping has to be adjusted. This will take a little time to change. I will tell you when next test is ready. (tomorrow i'm out of home, so i think saturday evening)

**Comment by NitroxPower** [comment] 2019-04-11 20:29
I really appreciate what you are doing and what you have done, fixing the building issues is the most important fix in my opinion i would like to help but i dont know C# so i can only help in testing or explaining other bugs etc.

**Comment by acidscorch** [comment] 2019-04-12 09:12
No need to devalue your work :) You are doing a great job! 

Coding for SN and Nitrox is a little bit like playing chess in a tunnel. For coding or following a process logic it is necessary to have 10, 20 or more steps ahead in mind for the current line of code that is need to be changed. And this could also create a tunnel view on the current issue or logic. 

So it is extremly helpful and absolut necessary that someone else is in account for the overview. Who manages the Issue list, identifies duplicate reports, consolidates issues that may relate to the same underlying code parts/logics, priorizes bugs (game-breaking, major, minor, etc) and tests changes for proper fixing and ensuring no new bugs or side effects of the changes.

So again, thank you very much for the help, the summary, the guidance and the testing.

**Comment by acidscorch** [comment] 2019-04-12 18:59
Hello NitroxPower,

New Client:
https://www.dropbox.com/s/9nay8bjshj8kify/AcidScorch%20-%20Beta%20-%20Building4.zip?dl=0

- same hints as above
- spawn fix integrated
- subnautica lib copy integrated (after checking the logs i've noticed, that there wasn't the right version of a library)
- only for the discord.dll you may have to check manually

**Comment by NitroxPower** [comment] 2019-04-13 08:32
From the first look it looks pretty good the solar panels arent flying, the reinforcements are working correctly, i will edit this message for further testing 
![Capture](https://user-images.githubusercontent.com/46358553/56077007-be1a5e00-5ddf-11e9-8998-0dc3d1d388b6.PNG)

**Comment by acidscorch** [comment] 2019-04-13 08:42
Good Morning,

don't wonder for flying lockers outside the Base. I'm currently testing objects placed in the small mini corridors that are generated when placing a hatch at a room.

**Comment by NitroxPower** [comment] 2019-04-13 10:22
If i use commands will it cause issues like spawn reactor cores so i can test it?

**Comment by acidscorch** [comment] 2019-04-13 10:27
Please don't use instantbuilding or spawn.

Events are needed for synchronisation, because full object information is only transfered at begin construction. The other packets have only state Change Infos to reduce Network Traffic.

You can "unlockall" for the blueprints and "item ... x " for the ingredients for using the builder-tool.

**Comment by NitroxPower** [comment] 2019-04-13 11:02
what if i do nocost?

**Comment by acidscorch** [comment] 2019-04-13 11:04
Hmm, don't know. I haven't tested it. Just try it :)

**Comment by NitroxPower** [comment] 2019-04-13 11:09
![Capture](https://user-images.githubusercontent.com/46358553/56078876-946c3180-5df5-11e9-8db9-7ae638240a18.PNG)
It seems that when you are inside a base and you rejoin the game thinks you are not in a base and i cant see the power i can swim and i dont have infinity oxygen

**Comment by acidscorch** [comment] 2019-04-13 11:11
Okay, i'll check this. As workaroud just use a hatch.

**Comment by acidscorch** [comment] 2019-04-13 11:29
A little question aside: how to make these nice CheckButton Lists here in a comment/issue?

**Comment by NitroxPower** [comment] 2019-04-13 11:32
![Capture](https://user-images.githubusercontent.com/46358553/56079139-f24e4880-5df8-11e9-8965-fe89897ccf3e.PNG)

**Comment by acidscorch** [comment] 2019-04-13 11:48
- Powersources aren't synced yet (i only  initiate the solar panels with 50% as a quick win solution) (later)
- State of Machines (Filtration, Biomass Amount) is also not synced yet (later)
- Fabricator at ModuleStation i have to check

For the moment let's try to focus on constructing/deconstructing themes to get a PR finished and let all object related things for later and let us adress them in separate issues (if they still appear after this has been merged to master). There are also some other things that (like hullbreak and repair state) that can only be synced if basic building syncing is stable running.

**Comment by NitroxPower** [comment] 2019-04-13 11:56
From saving all building stuff are perfect its just the sync of some stuff. Now for last thing we need at least 2 players in the server to see if the sync of building stuff if its right cause when we played together i saw some stuff having false position

**Comment by acidscorch** [comment] 2019-04-13 12:49
That are good news. 
Let me see, if i can fix the "player swimming" and the fabricators. I think those points are related to the changes i've made. The Alien Containment should also work (maybe not the contents synced, but should be able to put something in), maybe this is not finalized after placing. 
I'll inform you when i'm through with this. 

In the meanwhile, could you check out this and create an issue, if you think it's good and you are interested to coordinate the issue?
https://www.dropbox.com/s/9cwc5r0de1sy49a/SaveGame-Management%20-%20Enhancement%20-%20Help%20Wanted.zip?dl=0

**Comment by NitroxPower** [comment] 2019-04-13 12:58
Sometime before they disabled the save game button for multiplayer its still a thing? hmm lemme see what i can do

**Comment by acidscorch** [comment] 2019-04-13 13:00
maybe this is fixed in the latest master. (as noticed, my branch is a little bit behind :) )

**Comment by NitroxPower** [comment] 2019-04-13 13:01
idk how i can help with that one cause this is just a straight code the only thing i can test is if it works after you finish it

**Comment by acidscorch** [comment] 2019-04-13 13:10
I want to focus on the building thing and all that's related to the it directly with the subnautica logic. The savegame handling is more a nitrox-server thing and should be enhanced by someone else who has more knowledge there than i have. 
My intention was, that you check it, create the issue and coordinate/retest things, if someone else grabs the issue and works on it. (as a supervisor, not a coder :) )

**Comment by acidscorch** [comment] 2019-04-13 13:20
Have you also experienced this (Issue#788)? 
Could you relate this issue to this one?

**Comment by NitroxPower** [comment] 2019-04-13 13:36
I just used the latest version of Nitrox to see about the saving button. When you press it it starts to save but it never ends cause you are in multiplayer so cause it cant save you can quit the game and you have to press Alt+F4 to leave

**Comment by acidscorch** [comment] 2019-04-13 13:39
Yes, that's the known bug i also noticed and that was also communicated in discord. You said it was fixed a while ago, maybe it was lost in any of the changes since then. So let's keep it as checkbox on the list that the save button get's disabled in multiplayer mode.

**Comment by NitroxPower** [comment] 2019-04-13 13:42
I reported it as an issue #790

**Comment by acidscorch** [comment] 2019-04-14 12:20
https://www.dropbox.com/s/ek7cza5gl64btn5/AcidScorch%20-%20Beta%20-%20Building5.zip?dl=0

should fix:
- player in base doesn't swim after login
- fabricators
- solar panels lighting at night login (i removed the quick solution to give them 50% power after init)

for the other points:
- alien containment should work (get in and drop a fish from your hand). but the placed entitys aren't synced or saved on the server at the moment
- all states of interiour (filter progress, reactor fill state, door states, etc.) aren't coded at the moment. this will take some time, because it is individual for every object-type
- for the energy can drop to zero and no emergeny mode is triggered in the base i haven't found a solution. don't know if it comes from the game or if any of the already existing code in nitrox causes this or something is missed after initializing energy based objects

**Comment by acidscorch** [comment] 2019-04-14 20:50
Hey NitroxPower, 
Infy and me will be on tomorrow from 18:00 to 19:00 GMT/UTC. If you like, we can go for a 3 player real test.

**Comment by acidscorch** [comment] 2019-04-15 18:06
I'm online and testing :)

**Comment by NitroxPower** [comment] 2019-04-15 18:28
@acidscorch Ok i i will join now sorry i was busy these days and tommorow i will be missing all day

**Comment by NitroxPower** [comment] 2019-04-15 18:43
@acidscorch  try making a small base and build some stuff to it so i can check ithe sync when building is correct however i found some bugs with the fabricators i will report them later

**Comment by NitroxPower** [comment] 2019-04-15 18:58
Like i was afraid there are issues with the sync which means the saving is correct but while in-game if someone build something its not correct in other clients except if they rejoin:

- Solar Panel Fabricator seems that works perfectly but placing the upgrade module in the upgrades it doest save that and the Fabricator of the upgrade console doest give you the item when you build a module 
![Capture](https://user-images.githubusercontent.com/46358553/56157628-a3570d80-5fc8-11e9-806c-a7a75376bebe.PNG)
![Capture2](https://user-images.githubusercontent.com/46358553/56157685-c71a5380-5fc8-11e9-98e8-3086966cb62d.PNG)

- And the most important one is the sync when building it seems that all Base pieces  are getting build correctly but the rest of them (Exterior Modules,Interior pieces,Interior Modules,Miscellaneous) seem that position isnt correctly or even some stuff doest appear at all like the Reactors when you builded sometime 
![Capture3](https://user-images.githubusercontent.com/46358553/56157868-40b24180-5fc9-11e9-9193-6b6de50d9e34.PNG)
![Capture4](https://user-images.githubusercontent.com/46358553/56157891-4ad44000-5fc9-11e9-9aa6-e63290aa9cb5.PNG)
![Capture5](https://user-images.githubusercontent.com/46358553/56157905-51fb4e00-5fc9-11e9-92a4-7ccf72340148.PNG)

**Comment by acidscorch** [comment] 2019-04-15 19:44
Okay, thank you very much for the test assist :) 

Seems like we have the following issues:
- general player Z-position missmatch (i've seen you half a room-height below the ground), that's why furniture and other objects are not at the right height position 
- continous sync of constructing/deconstructing progress 
- lost packages between initial sync and finished loading (that's why some objects weren't constructed after relog. they were finished between your login start and final load-finish)
- items grabbed from and given to players nearby and not only from the one who is constructing/deconstructing
- moonpool module fabricator (i will check)
- module storage at maproom (this is separate and should go to a separate issue)

**Comment by Maydit** [comment] 2019-07-20 03:08
Here's a video of what the posters look like when you're not the one who places them: https://www.youtube.com/watch?v=Xz7KwLbXXWM
Funny bug.

**Comment by Jannify** [comment] 2021-05-09 14:53
Closing it because old and probably fixed.

**Closed by Jannify** 2021-05-09 14:53 UTC

**Comment by NILOIDE** [comment] 2025-08-16 22:11
Apologies for reopening such an old issue.

Anytime we restart a server, many rooms in our base become bugged. 
There seems to be little correlation with the player that constructed the room (we are two players) or the recency of construction of  the room.

List of distinct bugs:
- Rooms that have completely disappeared with their furniture remaining in place. We are still able to enter the rooms, but the floor/walls/ceiling appears to have no collision causing the player to fall through to the sea floor without the swimming animation to begin.
- Rooms that have partly disappeared. Examples: Connecting tunnels that have their middle floor panel seemingly removed (you can see through and it has no collision, causing the player to fall through).
- Rooms with bugged objects or disappearing objects altogether. Examples: Our Vehicle Upgrade Console disappears (including the wall indentation it creates with the "VEHICLE_NAME DOCKED" screen and the fabricator). We have a multi-purpose room with 2 water purifiers where one has disappeared (the older of the two purifiers).
- Objects highlighted as 'partially constructed' that were never placed by us. One of those objects appears to be a Vehicle Upgrade Console which may be related to the previous item in this list. The other object is a hatch in the middle of one of our 4-way connector hallways.

Here is an image of what our base looks like. 
At the bottom left you can the highlighted partially constructed object. On the right/top you can see a disappeared multi-purpose room with furniture still in it and disappeared hallways with lockers still in them.
<img width="2903" height="1238" alt="Image" src="https://github.com/user-attachments/assets/3a8fb463-27e5-4754-95de-c6ae5eafb8d6" />

**Comment by NinjaPedroX** [comment] 2025-08-16 22:18
@NILOIDE What version/build of Nitrox are you using?

**Comment by NILOIDE** [comment] 2025-08-16 22:23
@NinjaPedroX Nitrox Alpha V1.7.1.0

**Comment by oliver408i** [comment] 2025-08-16 22:24
> [@NinjaPedroX](https://github.com/NinjaPedroX) Nitrox Alpha V1.7.1.0

These issues should be fixed in 1.8 (the next update). I would test again once the update comes out

**Comment by NILOIDE** [comment] 2025-08-16 22:33
Any recommendations on what to do for now? We have been trying to dig through the json file with little success. We aren't familiar with Subnautica's base data structure (and we are new to the game). 

Will our current file be portable to the next version? Or does 1.8 require a new game file?
Will the issues in our file be fixed by the next version if we stop playing for now?

**Comment by NILOIDE** [comment] 2025-08-16 22:35
Also, thank you for the quick replies and the amazing work on this project.

**Comment by oliver408i** [comment] 2025-08-16 22:37
> Any recommendations on what to do for now? We have been trying to dig through the json file with little success. We aren't familiar with Subnautica's base data structure (and we are new to the game).
> 
> Will our current file be portable to the next version? Or does 1.8 require a new game file? Will the issues in our file be fixed by the next version if we stop playing for now?

Nothing much to do right now other than don't use bioreactors, nuclear reactors, or water filters, and keep your base size small. Don't go around and edit the json files if you don't know what you are doing.
1.8 will require a new game file, so you'll need to start over.
