### ISSUE TITLE
Seamoth randomly disappear or explode

### ISSUE THREAD

**Issue by MysticCoss** [SubnauticaNitrox/Nitrox#1223] opened 2020-08-19 12:28 UTC
With 1 vehicle bay we can not create more than one seamoth. We made 2 vehicle bay, then each person must launch their own seamoth. when enter other's seamoth it will sometimes disappear or explode

**Comment by Coding-Hen** [comment] 2020-09-12 09:53
Please verify this is still an issue. Are you able to provide the exact way you produced this? I am unable to reproduce.

**Comment by EnzoTools** [comment] 2020-09-16 11:45
> 请确认这仍然是一个问题。您是否能够提供产生此效果的确切方法？我无法复制。

Mine didn't explode, but it got stuck and couldn't move, so I had to use the booster to get home  :( 

After I restarted the server, he was back to normal, unable to move again a few minutes later

**Comment by EnzoTools** [comment] 2020-09-16 11:45
> Please verify this is still an issue. Are you able to provide the exact way you produced this? I am unable to reproduce.

Mine didn't explode, but it got stuck and couldn't move, so I had to use the booster to get home :(

After I restarted the server, he was back to normal, unable to move again a few minutes later

**Comment by MysticCoss** [comment] 2020-09-24 03:58
@Coding-Hen all things happened: i had to created 2 mobile vehicle bays, each person must create their own seamoth on their own MVB. After that we went to life pod under 200m. Because of the limitation we had to  park there and swam deeper. When we came back, my friend's seamoth disappeared. Maybe it was destroyed because of depth. We came back to base for him to build a seamoth again. We left those alone to do some stuffs. When we came back to base again, i entered my friend's seamoth and it exploded instantly.
It's kind of random event. I have tried reproduce but fail

**Comment by AzraeltheWicked** [comment] 2020-09-28 17:39
I can confirm the event, though not the cause.

I have gone into wrecks on multiple occasions and in multiple locations and when I come back out my seamoth will have vanished.  There's no sound or debris indicating explosion and in one case I was only on the other side of a wall (maybe 5m away).  Seamoth just vanishes.

**Comment by Ohimark12** [comment] 2020-10-15 13:52
yea this happened to me yesterday and it seems that it thinks your hitting something at a much faster speed than you are and does a ton of damage i just accidentally bumped into my friend and his seamoth blew up buuut we left the server and rejoined and it was back at low health.. but back thats all i have about this matter

**Comment by EinLuigi** [comment] 2020-11-30 20:15
it is true i can confirm it

**Comment by dartasen** [comment] 2020-12-14 00:59
New version of Nitrox is available, we shipped some fix for this. I'm closing it !

**Closed by dartasen** 2020-12-14 00:59 UTC
Labels: fixed on next release

**Comment by Xavego0n** [comment] 2023-01-16 19:06
i have an issue with seamoths everytime when i turn off the server then turn the server on again all seamoth are gone docked and undocked

**Comment by VaelophisNyx** [comment] 2023-05-03 01:13
Still occurring
