### ISSUE TITLE
Server Connection issue

### ISSUE THREAD

**Issue by MadrugsPlays** [SubnauticaNitrox/Nitrox#117] opened 2018-02-04 06:17 UTC
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/1692505/output_log.txt)

Hello! After setting everything up, I seem to be having some problems upon joining my own game (unless using localhost) or joining a buddy/having a buddy join me. Did I setup anything wrong?

PS: Patcher injected before bindings were setup

**Comment by Mickimoo2** [comment] 2018-02-04 23:37
From my understanding, it looks as though it can't make a connection to the server. Are you sure that you have port-forwarded the IP, and/or are using the outgoing (public) IPv4 of the network that you are testing on?

**Comment by MadrugsPlays** [comment] 2018-02-04 23:44
Hi! And thanks for the answer. Yes, I have portforwarded the port 11000 via TCP to my IP at my modem, though it seems my modem has an IP adress different than my public one, maybe it's my ISP's fault- I believe they have different "master rouiters" by region at my city, so even if I portforward or dmz, my access can still be denied via a certain port.
What I have noticed is, along the fact that they adress me a dynamic IP, some ports seem to be able to be open at certain IP. Either way, I will give them a call to try and get a Static IP, it's overrall way better.
By the way, just for added info I am connected directly by cable to my modem, not to a router.

Thanks for the help. But please do not close the thread as I am going to try and solve this, I could be wrong and this be a totally different error than I expect

**Comment by MadMaxOfYore** [comment] 2018-02-13 18:15
I think your understanding of the underlying connection issue is flawed. If you're using a modern cable modem that is provided by any major ISP participating in the market today, then it is a multi-purpose appliance that serves the functions of modem and router. You would not have been able to port forward on a stand-alone modem - that's router functionality. It is also to be expected that your public facing IP address would be different from the one assigned to your machine on your internal subnet. It does not matter if it is assigned dynamically or statically in this case.

FWIW- The dynamic IP address assigned to your by the ISP is generally leased to the MAC address of your gateway for two years on average. The only time you get a new one is when the gateway has been disconnected for a long period of time, you request a new one from the ISP for whatever reason, or you spoof the MAC address of your gateway appliance and restart it. Outside of those situations - your IP should not change for a long, long time. 

All that is required is to forward TCP traffic that the router receives on port 11000 to the machine that is running the Nitrox server. If you feel like you've done that correctly and are still having issues, then the only problem I can think of is that you're not entering the IP address of your gateway - or you have a firewall on your host machine that is blocking the traffic.

We are happy to hear feedback concerning any error messages that you receive, but getting the mod configured to run in your local environment is well beyond the level of support that we can offer for the immediate future.

We thank you sincerely for you interest in our work and we encourage you to continue to follow our progress as we continue to push towards a stable release. While this may seem harsh, please trust that we are just as vested in getting to play SN with our friends as all of you are - we wouldn't be doing this for free if we didn't share that goal with our audience.

I understand that you'd like to leave this issue open, but it unfortunately sets the tone that there is an underlying problem in the networking capabilities of Nitrox that does not exist. As such, I am going to close this issue as I do not see any evidence that the root cause here has anything to do with the Nitrox implementation

Thanks Again!
-MadMax

**Closed by MadMaxOfYore** 2018-02-13 18:15 UTC
Labels: question
