### ISSUE TITLE
Can't construct the Cyclops

### ISSUE THREAD

**Issue by Atheneos98** [SubnauticaNitrox/Nitrox#1494] opened 2021-05-30 19:50 UTC
Nitrox version : 1.4.0.0 

### Bug
We tried to build the cyclops normally by the vehicle constructor, and litteraly nothing happened. I was pushing the button (With all the components in my inventory) and the cyclops did not appear. We also tried to make it spawn with the command console, same problem.

### Expected
 By pushing the button, the cyclops should have start to construct in front of the vehicle constructor 
### Steps to reproduce
Just hop on the constructor platform, try to make spawn the cyclops

**Comment by gituser6342** [comment] 2021-05-31 10:33
Had the bug too. Couldn't build second vecicle. 

Workaround: Build a second vehicle station.

**Comment by dartasen** [comment] 2021-05-31 21:41
Duplicate of #1461, i'm closing this one

**Closed by dartasen** 2021-05-31 21:41 UTC
