### ISSUE TITLE
[Spawn] Spawn points loading

### ISSUE THREAD

**Issue by Alberto247** [SubnauticaNitrox/Nitrox#176] opened 2018-02-26 19:40 UTC
Looks like some spawn points(SafeShallows_TechSite for example) don't get loaded. However, some entities can only spawn there, so they never spawn.
Can you please check if it happens to others too?

**Comment by MarijnS95** [comment] 2018-02-26 20:10
The code for calculating cell positions was incorrect, this might've caused unintentional culling/deferring of those spawn packets. This has recently been fixed and merged in https://github.com/SubnauticaNitrox/Nitrox/pull/171, can you ensure you have those commits and test again?

**Comment by Alberto247** [comment] 2018-02-26 20:29
I updated it to #171 and it still seems not to load some spawnpoints. Can someone confirm that please?

**Comment by MarijnS95** [comment] 2018-02-26 20:30
Can you check if the server loads them?

I remember there are some raw files involved that were uploaded by the maintainer. I haven't checked yet but it's likely these are outdated.

**Comment by Alberto247** [comment] 2018-02-26 20:37
I'm checking on the server side, and they don't get loaded. I've checked the raw files and they are still up to date with the ones inside Subnautica's resources.

**Comment by Alberto247** [comment] 2018-02-26 21:53
However, I think the problem is not in the raw files, because during the load from the batch cells those spawn points are not loaded.

**Comment by nesrak1** [comment] 2018-02-26 22:52
I think all of the raw files can be removed now, I'm not absolutely sure but I think assetstools reads all of them from the resources.assets file (hence the resources.assets error everyone has been getting)

**Comment by MarijnS95** [comment] 2018-02-26 22:54
@nesrak1 Yeah that would be cool, it was even intended as such:
https://github.com/SubnauticaNitrox/Nitrox/blob/fc8ea7f01c3ba196297f20d2900eab87e938c791/NitroxServer/Serialization/WorldEntityDataParser.cs#L10-L17

**Comment by nesrak1** [comment] 2018-02-26 23:42
World data for sure is already being read from worlddata and lootdist https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer/GameLogic/Spawning/EntitySpawner.cs#L133

**Comment by Sunrunner37** [comment] 2018-03-03 08:48
@Alberto247 were you able to collect any additional data points on this one?

**Comment by Alberto247** [comment] 2018-03-03 10:30
I logged all spawnPoint loaded and made sure some are not loaded. However i can't fix this myself as i have no idea where it cames from or how to work with those batch files.

**Comment by Sunrunner37** [comment] 2018-03-11 08:29
Can you check to see if this is still an issue?  I recently pushed a change to allow statically placed items to spawn.  This may be some of those missing items.

**Comment by Coding-Hen** [comment] 2020-04-29 19:26
@Alberto247 Are you able to retest this?

**Comment by Alberto247** [comment] 2020-04-30 12:32
@Coding-Hen I havn't been looking at this project for two years, I missed a lot of updates on the subject.
Moreover, i'm currently in lockdown and my PC is in my apartment where i cannot go. I'll be able to check this in more or less a month, so if someone else can do that it would be better.

**Comment by dartasen** [comment] 2020-11-23 21:10
This is an old issue, can't reproduce with the latest version.
Also the mod has drastically changed in 2 years, so I'm closing it.

**Closed by dartasen** 2020-11-23 21:10 UTC
