### ISSUE TITLE
Scanable items

### ISSUE THREAD

**Issue by KBTKraft** [SubnauticaNitrox/Nitrox#151] opened 2018-02-10 14:37 UTC
None of the randomly spawning items are there is this a known issue or is it just my game

**Comment by al-darwish** [comment] 2018-02-10 15:30
U mean blueprints?

**Comment by KBTKraft** [comment] 2018-02-10 15:30
Yeah the items for the blueprints

**Comment by Alberto247** [comment] 2018-02-10 19:52
Just your game, are you sure that there are no errors while launching the server?

**Comment by KBTKraft** [comment] 2018-02-10 20:09
Yeah I am sure i have cheeked all the places i can think of Where else should i be looking

**Comment by MarijnS95** [comment] 2018-02-10 21:36
From the top of my head I can't remember seeing code that explicitly disables these elements. I do know for sure though that these items are not synced through the server yet. You could say it's a `known missing feature`, not a bug.

**Comment by MadMaxOfYore** [comment] 2018-02-13 17:48
Hey @MarijnS95, do we have a story in the backlog to address this? I just took a peak and didn't see it anywhere, but it may be implicitly captured in one of the other cards. I'll create a card and close this issue if that needs to happen.

**Comment by MarijnS95** [comment] 2018-02-13 21:59
@MadMaxOfYore I can't find it either, and like I mentioned I can't remember explictly disabling these from spawning - work must've been done on it in some way, or other patches affect the spawning of said items. Feel free to create a new card.

**Comment by MadMaxOfYore** [comment] 2018-02-13 22:32
We've capture this work item. Feel free to check in on progress periodically at #161 

Thanks,
-MadMax

**Closed by MadMaxOfYore** 2018-02-13 22:32 UTC
