### ISSUE TITLE
Infinite Loading Multiplayer

### ISSUE THREAD

**Issue by Yarin111** [SubnauticaNitrox/Nitrox#521] opened 2018-12-26 17:41 UTC
I join into a server and its says "Loading Multiplayer" and doesnt continue anyway to fix it?

there is my output_log if its needed: https://pastebin.com/raw/8zPiMquf

**Comment by Darkluke11** [comment] 2018-12-26 20:53
It's the same by me if you find something out pls tell me the solution

**Comment by Coding-Hen** [comment] 2019-12-30 17:36
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
