### ISSUE TITLE
Inventories base/player/storage won't save when closing server

### ISSUE THREAD

**Issue by NekoDm** [SubnauticaNitrox/Nitrox#1002] opened 2020-03-28 14:50 UTC

**Comment by TheClockTwister** [comment] 2020-03-28 15:11
@Coding-Hen This issue may be closed. Blank duplicate of #1003

**Comment by TheClockTwister** [comment] 2020-03-29 16:27
@Sunrunner37 This issue may be closed. Empty duplicate of #1003

**Closed** 2020-03-29 17:45 UTC
