### ISSUE TITLE
cyclops power running out very quick

### ISSUE THREAD

**Issue by Lt0Tactical** [SubnauticaNitrox/Nitrox#1976] opened 2023-01-23 14:36 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

cyclops power seems to be running out incredibly quickly, barely lasting 2-3 minutes. also I think it was exponentially getting worse?

### Describe the steps you took to encounter the bug.

play the game while using cyclops a lot with a 2nd player using another vehicle

**Comment by JKX-Jakubix** [comment] 2023-01-23 19:59
Same issue here.

**Comment by The-Great-Sephiroth** [comment] 2023-02-17 22:33
Are you guys running on silent or max speed? I played with a friend for HOURS yesterday on our server. I built the cyclops and we travelled al over in it, carrying around a prawn suit and using it also. Battery drain in both vehicles was normal. Do we both need to by in cyclops subs to trigger this?

**Comment by Jannify** [comment] 2024-01-09 02:01
Duplicate of #1293

**Closed by Jannify** 2024-01-09 02:01 UTC
Labels: Type: bug, Status: to verify
