### ISSUE TITLE
Version Outdated

### ISSUE THREAD

**Issue by Luca04081** [SubnauticaNitrox/Nitrox#1271] opened 2020-10-31 18:43 UTC
### Version
 Alpha 1.3.0.0_RC2

### Bug
 I tried playing mulitplayer with my friends today and we all downloaded version 1.3.0.0_RC2, my friends could join my server but I just couldn't, it gave me this error message: Your Nitrox installation is out of date. Server: 1.3, Yours: 1.2. I tried everything I can like re-installing Nitrox and puting the new files into the subnautica directory (overwriting the old ones).

### Steps to reproduce
I tried updating Nitrox to a new version, I don't know what happend.

### Other details:
If I open the log it says that:
[19:19:48 Client INFO]: Completed patching using NitroxPatcher, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null

**Comment by Coding-Hen** [comment] 2020-11-01 12:03
Duplicate of #1263 
To update Nitrox from 1.2 to 1.3

1. Go to your Subnautica installation (example is for Steam but Epic is similar). Example:
    C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data
    Delete the "Managed" folder.
2. Verify game files (for Steam see image below. For Epic see link https://discordapp.com/channels/525437013403631617/525438387105038346/742818099086229514)
3. Download and install Nitrox: https://nitrox.rux.gg/ or see download links in #📢announcements (do not use old installation, remove it instead)
4. Extract the Nitrox zip somewhere you like and run the launcher.

**Closed by Coding-Hen** 2020-11-01 12:03 UTC
