### ISSUE TITLE
Issue with Multiplayer launch

### ISSUE THREAD

**Issue by Mefni** [SubnauticaNitrox/Nitrox#856] opened 2019-11-18 17:47 UTC
I can't Launch the Multiplayer game, Singleplayer works fine but when i try to start Multiplayer it says that my file path is incorrect

![Path](https://user-images.githubusercontent.com/57913787/69076454-cbfa2680-0a33-11ea-8a71-818d2b7e3e55.PNG)
![Error](https://user-images.githubusercontent.com/57913787/69076460-d0264400-0a33-11ea-8a5a-dff241814906.PNG)

**Comment by Coding-Hen** [comment] 2019-11-18 17:50
Currently there is no fix for this on the current version of subnautica. You can downgrade following the instructions on discord to play running the older version.
Duplicate of #848

**Comment by MrSaussissonSec** [comment] 2019-11-18 18:33
@Coding-Hen can you give a link to the discord server ? I don't know how to join it and didn't managed to find any link to it. Thx ofr helping us ! :)

**Comment by Hardcor3UK** [comment] 2019-11-18 18:36
https://discord.gg/sF8ynqc

**Closed** 2020-03-19 23:05 UTC
