### ISSUE TITLE
My game does not open

### ISSUE THREAD

**Issue by Magic1000** [SubnauticaNitrox/Nitrox#806] opened 2019-05-13 22:05 UTC
Me and my friend were playing, and we decided to leave, when we came back and reopened the game he stayed in infinite loading, help please

[nitrox-2019-05-10.log](https://github.com/SubnauticaNitrox/Nitrox/files/3174995/nitrox-2019-05-10.log)
[nitrox-2019-05-11.1.log](https://github.com/SubnauticaNitrox/Nitrox/files/3174996/nitrox-2019-05-11.1.log)
[nitrox-2019-05-11.log](https://github.com/SubnauticaNitrox/Nitrox/files/3174997/nitrox-2019-05-11.log)

This is my recent log, If somebody can help me, I'll be happy.

**Comment by Coding-Hen** [comment] 2019-12-30 17:35
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
