### ISSUE TITLE
Subnautica singleplayer sound glitch

### ISSUE THREAD

**Issue by DagrMine** [SubnauticaNitrox/Nitrox#557] opened 2019-01-01 18:04 UTC
Earlier today I had to uninstall nitrox because when I started a singleplayer game it kept the music from the loading screen going when I loaded in and all of the sound effects (thermoblade, knife, hatch, etc...) didn't work. For some reason the dialogue still worked. Hope someone finds this useful

**Comment by jayjar291** [comment] 2019-01-02 21:43
same here

**Comment by jimmyvbuck01** [comment] 2019-01-03 00:33
Same but only my music is screwed up, when I turn it off all the other sound effects work

**Comment by eliw00d** [comment] 2019-01-04 05:33
This happens to me as well, but after some period of time it starts working again.

**Comment by RylenWolf** [comment] 2019-01-05 02:09
If mods are curious, this bug fixes itself for me when a different track plays. Specifically, entering the Observatory plays a specific audio, and that fixes the problem for me. I suspect it's related to the music for the menu just not being told to stop by anything else.

**Comment by jimmyvbuck01** [comment] 2019-01-05 02:12
> This bug fixes itself for me when a different track plays. Specifically, entering the Observatory plays a specific audio, and that fixes the problem for me. I suspect it's related to the music for the menu just not being told to stop by anything else.

It must have something to do with how the mod edits the main page by adding the multiplayer tab to it. I uninstalled the mod and now the sound works fine, I don't plan to play again for a few weeks so I will just play singleplayer till then.

**Comment by LaikaIwanowa** [comment] 2019-01-05 16:13
Here's how to fix it: Enter another biom than the one you were when you loaded the save. That way the music and sound go back to normal.

**Comment by RylenWolf** [comment] 2019-01-24 16:04
@caroga my idea is to open a ticket on the issue, wait for coders to see it, and help players with workarounds until the issue is fixed.

**Comment by eliw00d** [comment] 2019-01-24 16:05
@Caroga I believe that is the goal: https://github.com/SubnauticaNitrox/Nitrox/pull/599#issuecomment-452379504

**Comment by Coding-Hen** [comment] 2020-04-28 22:41
@Measurity this can probably be closed as single player is disabled

**Closed** 2020-04-29 07:55 UTC
