### ISSUE TITLE
Many texture display issues

### ISSUE THREAD

**Issue by grichka** [SubnauticaNitrox/Nitrox#1269] opened 2020-10-29 21:02 UTC
### Version
Alpha 1.3.0.0_RC2

### Bug

When playing with 2 players it is frequent not to see the other player at all, at a wrong place or with broken textures falling down like when using the prawn, as you can see on following screenshots:

![20201027231958_1](https://user-images.githubusercontent.com/1225647/97632047-3da76680-1a32-11eb-9e75-9a06672f2a93.jpg)

![20201027232001_1](https://user-images.githubusercontent.com/1225647/97632058-40a25700-1a32-11eb-8b71-e9cc2d67274f.jpg)

Prawn is frequently invisible too.

**Comment by dartasen** [comment] 2020-11-21 18:41
Hi @grichka,
I tried to reproduce the bug but I didn't succeed, do you have any steps that we can follow?
Because I don't think it's a nitrox related bug

**Comment by grichka** [comment] 2020-11-23 18:18
Each time we played (2 players) with this version, one player taking a prawn, and the other one taking a seamoth or just swimming in the area, there were : 
- desync issues
- wrong player position
- player is invisible to its teammate but his actions like mining can be seen by the other player.
- prawn texture was seen like on the screenshot anytime it was leaving the cyclops or a building.

If you can't reproduce these bugs, with the version Alpha 1.3.0.0_RC2, then what could I share to help you investigate the issue?

**Comment by dartasen** [comment] 2020-11-23 18:54
Alright, do you use hamachi (or something similar) or port forwarding ?

Well if you can do a game session, I would like to have the server log (which can be found in /Nitrox Logs/ at the root of the launcher for the person who is hosting) and the two player logs ( which can be found here : %AppData%\..\LocalLow\Unknown Worlds\Subnautica\Player.log)

If I can't see anything from these, I would like to join a game session with you

**Comment by dartasen** [comment] 2020-12-13 13:24
No update, I'm closing it for now.

**Closed by dartasen** 2020-12-13 13:24 UTC
Labels: Out of scope
