### ISSUE TITLE
Radiation state not restored upon joining server

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [SubnauticaNitrox/Nitrox#1987] opened 2023-02-17 22:26 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Upon restarting a server or even rejoining a server you played on where you stopped the radiation, the radiation state is not restored. It always treats it as if the player never entered the Aurora and never sealed the reactor leaks. This makes a huge area of the map inaccessible due to needing a rebreather but being required to use the radiation suit.

### Describe the steps you took to encounter the bug.

A friend and I started a new game on a dedicated server, played until we sealed the reactor leaks, and then quit the game for a break. Several hours later we joined the server and radiation was all the way up to where the shallows border the blood kelp zone. Shutting down and restarting the server does not cure this issue.

**Comment by Measurity** [comment] 2023-02-18 08:59
Duplicate of #1454 (tracked there)

**Closed by Measurity** 2023-02-18 08:59 UTC
Labels: Type: bug, Status: to verify
