### ISSUE TITLE
Multiplayer Interface not showing up

### ISSUE THREAD

**Issue by SkidFlashys** [SubnauticaNitrox/Nitrox#274] opened 2018-07-29 17:00 UTC
When I click on the "Multiplayer" Tab, nothing happens

**Comment by SkidFlashys** [comment] 2018-07-29 17:12
Also, when I click on "Options", the game crashes

**Comment by Measurity** [comment] 2018-07-30 00:06
Could you upload the output log? It's located here: `..\steamapps\common\Subnautica\Subnautica_Data\output_log.txt`.

Also, make sure the injected `NitroxPatcher.Main.Execute()` is in the right location:
https://i.imgur.com/mUachvA.png

**Comment by Gumby37** [comment] 2018-08-10 04:30
Right in this part prior to compiling. 
https://i.imgur.com/Si08Hgp.png

**Comment by Measurity** [comment] 2018-08-10 07:40
@Gumby37 That's the wrong location. You'll get keybinding exceptions because Nitrox hooks `GameInput.bindings` which shouldn't be changed after `GameInput.Initialize()`.

**Comment by AlexejheroYTB** [comment] 2018-08-10 13:37
Duplicate of #196

**Closed** 2019-01-13 19:45 UTC
