### ISSUE TITLE
Ore desync intentional?

### ISSUE THREAD

**Issue by sarayuuki** [SubnauticaNitrox/Nitrox#1883] opened 2022-10-27 19:59 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Me and boyfriend are running latest commit, this is more of a question then  a complaint.

is it normal for ore to not be synced when my friend broke the ore, but on my end it still is unbroken? like it didn't disappear, is this an intended feature?

### Describe the steps you took to encounter the bug.

boyfriend proceeds to break ore outcrop, any type. breaks on his end, but my side i don't see that he broke it.

**Comment by Jannify** [comment] 2022-10-28 07:23
Duplicate of #1701

**Closed by Jannify** 2022-10-28 07:23 UTC
Labels: Type: bug, Status: to verify

**Comment by Jannify** [comment] 2022-10-28 07:35
Duplicate of #1701
