### ISSUE TITLE
[Base] Hull integrity bug

### ISSUE THREAD

**Issue by Logharaa** [SubnauticaNitrox/Nitrox#1030] opened 2020-04-10 07:07 UTC
Playing at 3, in the same base we didn't have the same hull integrity. As a result, one player saw the base sinking, while the others did not.

**Comment by frgbf** [comment] 2020-04-13 18:17
I have the same problem in my game, it looks like that deconstructing structures is not synchronizing properly, which may cause your problem

I found the following trace in the logs
```
[17:11:34 Client ERROR]: Error processing packet: [DeconstructionCompleted Id: a9656f85-984d-4dca-86ff-eb3aeb15c5a7]
NitroxModel.DataStructures.Util.OptionalEmptyException`1[UnityEngine.GameObject]: Optional <T> is empty:
	Game object required from id: a9656f85-984d-4dca-86ff-eb3aeb15c5a7
  at NitroxModel.Helper.Validate.IsPresent[T] (NitroxModel.DataStructures.Util.Optional`1[T] opt, System.String message) [0x0000f] in <b8ae7171f8254f8aaab8bc7d8e9c91e7>:0 
  at NitroxClient.MonoBehaviours.NitroxEntity.RequireObjectFrom (NitroxModel.DataStructures.NitroxId id) [0x00013] in <574153703ef24f60b801a84a2ebd5879>:0 
  at NitroxClient.Communication.Packets.Processors.DeconstructionCompletedProcessor.Process (NitroxModel.Packets.DeconstructionCompleted packet) [0x00006] in <574153703ef24f60b801a84a2ebd5879>:0 
  at NitroxClient.Communication.Packets.Processors.Abstract.ClientPacketProcessor`1[T].ProcessPacket (NitroxModel.Packets.Packet packet, NitroxModel.Packets.Processors.Abstract.IProcessorContext context) [0x00000] in <574153703ef24f60b801a84a2ebd5879>:0 
  at NitroxClient.MonoBehaviours.Multiplayer.ProcessPackets () [0x00040] in <574153703ef24f60b801a84a2ebd5879>:0 
```

**Comment by tomi1206** [comment] 2020-04-14 07:15
The same things happen for us (2 on a server). But more of that, when reconnection to the server, some base fragment aren't complete anymore, hull integrity can be negative and the base sinking

**Comment by acidscorch** [comment] 2020-05-16 19:05
This issue adresses 2 themes:
1. On reconnect bases are not restored correctly or restored in the wrong order which causes a funtional Base to break and sink. This is noticed for current rework and Objects will be loaded correctly and in the right order.
2. Hull Integrity of Bases isn't synced between clients nor stored on server. This is a minor issue (assuming reinforcement sync is correct), because it may only be needed in case of not taking caution to overall base integrity and can be easily fixed by players themselves. If anyone is interested to implement syncing this, please contact me.

Best regards

**Comment by Jannify** [comment] 2021-05-09 16:47
Duplicate of #130

**Closed by Jannify** 2021-05-09 16:47 UTC
