### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by ELECTRO88888** [SubnauticaNitrox/Nitrox#819] opened 2019-06-27 15:55 UTC
Hello! I have seen that a lot of people have this issue, but, none of the fixes work for me...
I am trying to play subnautica with my friend, we are using hamachi, and it is stuck on saying loading...
and
loading multiplayer...

Please help... This is very annoying.

**Comment by SFRacing** [comment] 2019-07-17 16:15
same here.
A friend and i played together for 3 days. today we got infinite loading screens too.
Log file:
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3402798/output_log.txt)


I hope there is a fix for this ;(

**Comment by Coding-Hen** [comment] 2019-12-30 17:31
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
