### ISSUE TITLE
hey need help how to inject?

### ISSUE THREAD

**Issue by werichff** [SubnauticaNitrox/Nitrox#92] opened 2018-01-27 20:01 UTC
Inject NitroxPatcher into Assembly-CSharp:

    Load up dnspy
    Find a suitable method that gets executed before the actual game starts (GameInput.Awake() for instance)
    Add a reference to NitroxPatcher. This should be in the same directory as Assembly-CSharp. If not, follow step 3 more carefully.
    Inject startup code: NitroxPatcher.Main.Execute().

how to do it?

**Comment by MarijnS95** [comment] 2018-01-27 20:05
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/91.

**Comment by Staudey** [comment] 2018-01-27 20:05
Copied from another issue report:

"Download dnSpy from releases here: https://github.com/0xd4d/dnSpy/releases
Save the files from the .zip somewhere on your computer (I recommend ProgramFiles because it's a program).
Launch dnSpy from the dnSpy.exe (there are many files but it's there somewhere)
Inside dnSpy, hit ctrl+O(as in Open) or File->Open.
Navigate to Subnautica game directory and find CsharpAssembly.dll. Should be here: Steam\steamapps\common\Subnautica\Subnautica_Data\Managed\Assembly-CSharp.dll
Select and tell dnSpy to open it.
dnSpy should add new entrys on the left most list. Find "Assembly-Csharp" and select it.
In dnSpy click the search icon at the top of the program and type "GameInput".
At the bottom of dnSpy it should show "GameInput" and other classes of the game, find "GameInput" and double click it to open it in the edit view.
Press ctrl+F and now search for Awake. It should navigate you to: private void Awake(). That is the method you need to change.
Put the cursor inside that method (between the { and }) and press ctrl+shift+e.
dnSpy should open a new window. At the bottom left of that window click the open file icon.
In the open file dialog select NitroxPatcher.dll. If you followed all instructions prior it should be besides the CSharp-Assembly.dll you found earlier (same directory). If not, redo those instructions (mainly, building with Visual Studio).
After you opened NitroxPatcher.dll it should close the open file dialog and you're back at the Awake method.
Add the following to the bottom of that method (on the line before the close bracket }): NitroxPatcher.Main.Execute();.
Hit compile on the bottom right of the window. Wait for it to finish.
Close dnSpy (just hit all the X buttons on all the windows in order) and tell it to save everything (say yes and ok)."

**Comment by werichff** [comment] 2018-01-27 20:09
love you :D thanks so much :)

**Closed** 2018-01-27 20:29 UTC

**Comment by Pantking** [comment] 2018-01-27 20:36
![1](https://user-images.githubusercontent.com/35876439/35476059-adb65f80-03ba-11e8-80d8-d1d8eeb9c07b.png)

Where to write this :

Add the following to the bottom of that method (on the line before the close bracket }): NitroxPatcher.Main.Execute();.

**Comment by Measuring** [comment] 2018-01-27 20:44
@Pantking The guide should be clear enough for anyone with programming experience. We expect this from people that want to test/help out this mod because the mod is not stable yet. It won't be enjoyable for you.

If you want to help out developing this mod I recommend learning a bit of C#/programming. The docs can help you out a lot:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/methods

**Comment by Pantking** [comment] 2018-01-27 21:12
Where to get

NitroxPatcher.dll

i can't find in your Subnautica installation folder
