### ISSUE TITLE
Radiation state not synced

### ISSUE THREAD

**Issue by Szczurowsky** [SubnauticaNitrox/Nitrox#1757] opened 2022-03-06 22:41 UTC
### Version
1.6.0.0 Alpha

### Bug
After sucessfully fixing aurora engines by me and friend (both did it separately) and getting message about fixing it succesfully and relogin radiation still exists. Even when disabled by `radiation` command it's still not disabled after re-login

### Expected
Radiation state is disabled - doesn't affect players

### Steps to reproduce
Fix the Aurora engines by 2 players separatly and try to re-login

**Comment by Joan68** [comment] 2022-04-03 13:11
Same issue here

**Comment by tornac1234** [comment] 2022-04-03 13:22
Duplicate of #1454

**Closed** 2022-05-20 12:37 UTC
Labels: Type: bug, Status: duplicate
