### ISSUE TITLE
Entities spawning in wrong location and duplicate entities (moonpool and filtration plant)

### ISSUE THREAD

**Issue by TheStyxo** [SubnauticaNitrox/Nitrox#1410] opened 2021-01-23 11:56 UTC
### Version
Nitrox Alpha V1.4.0.0

### Bug
Entities are spawning in the wrong location and sometimes multiple entities spawning on server restart...
Specifically the MoonPool and FilterationPlant....

### Steps to reproduce
Server restart after making a moonpool or filteration plant

### Other details:
![image](https://user-images.githubusercontent.com/63962807/105577492-0bdb3d00-5da0-11eb-9a17-3e06cf38867c.png)

**Comment by Exso12Ecesis** [comment] 2021-01-24 15:41
This is (again for like the 5th time) a duplicate of #1400.

**Closed** 2021-05-09 15:05 UTC
