### ISSUE TITLE
Base Power Desync

### ISSUE THREAD

**Issue by ctrLd147** [SubnauticaNitrox/Nitrox#2179] opened 2024-09-20 09:33 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Power supply desync, issue is already opened somewhere, causes some people to see reactors etc, but some cant

**Comment by Jannify** [comment] 2024-09-20 11:24
Duplicate of fixed base building (on master) or already existing #1811

**Closed** 2024-09-20 11:23 UTC
Labels: Type: bug, Status: to verify
