### ISSUE TITLE
Play multiplayer not working

### ISSUE THREAD

**Issue by obamagaming6** [SubnauticaNitrox/Nitrox#1347] opened 2020-12-29 16:11 UTC
### Bug

when i click on play multiplayer in the launcher it takes me to normal subnautica, in the subnautica menu there is just the play option, not the multiplayer option that my friend has. For what i know i've done the exact same process as him, but i dont get the multiplayer game.

**Comment by Coding-Hen** [comment] 2020-12-29 16:18
Duplicate of #1311

I would suggest that you check out the discord server you can see the fix there. Also if you have a look at the duplicated issue you can see the steps there too.

**Closed by Coding-Hen** 2020-12-29 16:18 UTC
