### ISSUE TITLE
Freeze every 15 sec

### ISSUE THREAD

**Issue by Oryx84** [SubnauticaNitrox/Nitrox#1412] opened 2021-01-27 12:57 UTC

**Comment by Coding-Hen** [comment] 2021-01-27 13:01
Having some information here would be useful to understand what you are doing that is facing this. However I suspect it is when you first time you go into a new area and it has to generate which is just normal nitric behaviour and not a bug. I'm going to close this, reopen if this is not the case and you have more information.

**Closed by Coding-Hen** 2021-01-27 13:01 UTC

**Comment by Oryx84** [comment] 2021-01-27 13:05
there are no more details i play nitrox normally but every 15 seconds i have a little freeze and it's really annoying whereas when i play subnautica there is no freeze and the game is smooth
