### ISSUE TITLE
 When I rejoin the server, the fire extinguisher is completely full again (this has already been fixed for batteries)

### ISSUE THREAD

**Issue by EinLuigi** [SubnauticaNitrox/Nitrox#1326] opened 2020-12-17 18:27 UTC
Join your server richtflick with fire extinguisher then it is lower
if you rejoin than its completly full

**Comment by Measurity** [comment] 2020-12-17 18:28
Duplicate of #1251

**Closed by Measurity** 2020-12-17 18:28 UTC
