### ISSUE TITLE
Only one player can use battery charger or fabricator/seamoth docking issues

### ISSUE THREAD

**Issue by komarfamily** [SubnauticaNitrox/Nitrox#1152] opened 2020-06-23 20:31 UTC
Only one player can use fabricator or battery charger as it seems to be powered down for the other player. To solve this the other player can deconstruct and reconstruct it.

Also if one player builds a base, after leaving and returning to the game, it will lose the legs and just floats around and the solar panels are not connected to the base. They need to be de- and reconstructed again to power up the base.

Seamoth blows up when docking in the submarine.

Anyway keep up the good work amazing development so far. THX

**Comment by Jannify** [comment] 2020-07-02 17:23
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/685

**Closed by Jannify** 2020-07-02 17:23 UTC
