### ISSUE TITLE
drill arm noise glitch

### ISSUE THREAD

**Issue by Gramphop** [SubnauticaNitrox/Nitrox#1710] opened 2022-01-17 08:35 UTC
### Version
latest

### Bug
drill arm wont shut up

### Expected
it stops making noise, but no forever drill arm

### Steps to reproduce
just use the drill arm

### Other details:
no

**Comment by tornac1234** [comment] 2022-01-17 09:37
duplicate of [Issue#1612](https://github.com/SubnauticaNitrox/Nitrox/issues/1612)

**Closed** 2022-01-17 09:53 UTC
