### ISSUE TITLE
Seamoth docking

### ISSUE THREAD

**Issue by BearSixteenTwelve** [SubnauticaNitrox/Nitrox#1317] opened 2020-12-13 19:15 UTC
Alpha 1.3.0.0 Version
The latest version
1.3.0.0

### Bug
Seamoth is destroyed after docking in cyclops

### Expected
Seamoth docks in cyclops, plays animation of getting out, when animation is finished seamoth gets destroyed 

### Steps to reproduce
1. have both cyclops and seamoth (usually owned by 2 different people)
        2. have person with seamoth dock into cyclops owned by other person
        3. seamoth is destroyed (although the person that created the cyclops can dock the seamoth without breaking, when it is 
        undocked it gets destroyed

### Other details:
Usually the player that built  cyclops can dock their own seamoth, but there is a chance that seamoth will break. However if someone that didn't build the cyclops docks the seamoth it destroys it after the animation is played (have not tried this with prawn suit)
 None that i can find

**Comment by Coding-Hen** [comment] 2020-12-13 19:17
Duplicate of #1223

**Closed by Coding-Hen** 2020-12-13 19:17 UTC
