### ISSUE TITLE
Bug that prevents playing new radio messages

### ISSUE THREAD

**Issue by CharlesMod** [SubnauticaNitrox/Nitrox#1611] opened 2021-09-23 03:37 UTC
### Version

V1.5.0.1
### Bug

Trying to play a blinking radio message results in nothing happening, and the blinking going away.
### Expected

If the radio is blinking I should be able to answer it and a new radio message will play. 

### Steps to reproduce

Have ~106 story goals completed, wait for awhile until a radio message appears, try to play the radio to no effect, blinking goes away until another message eventually arrives and the same thing happens again

### Other details:

exception that printed to the console:

[21:31:15.849] Exception while processing packet: NitroxModel.Packets.RadioPlayPendingMessage
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at NitroxModel.DataStructures.ThreadSafeCollection`1.RemoveAt(Int32 index) in NitroxModel\DataStructures\ThreadSafeCollection.cs:line 188
   at NitroxServer.Communication.Packets.Processors.RadioPlayPendingMessageProcessor.Process(RadioPlayPendingMessage packet, Player player) in NitroxServer\Communication\Packets\Processors\RadioPlayPendingMessageProcessor.cs:line 21
   at NitroxServer.Communication.Packets.Processors.Abstract.AuthenticatedPacketProcessor`1.ProcessPacket(Packet packet, IProcessorContext player) in NitroxServer\Communication\Packets\Processors\Abstract\AuthenticatedPacketProcessor.cs:line 10
   at NitroxServer.Communication.Packets.PacketHandler.ProcessAuthenticated(Packet packet, Player player) in NitroxServer\Communication\Packets\PacketHandler.cs:line 45
   at NitroxServer.Communication.Packets.PacketHandler.Process(Packet packet, NitroxConnection connection) in NitroxServer\Communication\Packets\PacketHandler.cs:line 33
   at NitroxServer.Communication.NitroxServer.ProcessIncomingData(NitroxConnection connection, Packet packet) in NitroxServer\Communication\NitroxServer.cs:line 79

**Comment by tornac1234** [comment] 2021-09-23 06:12
Duplicate of Issue#1368

**Closed** 2021-09-23 08:37 UTC
Labels: Type: bug, duplicate
