### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#366] opened 2018-12-17 01:33 UTC
After reinstalling subnautical and installed new game files, I am now showing such an error in the console I created a folder SNUnmanagedData there and I copied the dish from Build18 but nothing helped, there are still few fish and no schemes

[Nitrox] I: Unable to find batch cells file 'D:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-10-16-14-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Ten\Documents\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.

**Comment by Sajgoniarz** [comment] 2018-12-17 14:32
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/188

**Closed** 2019-01-13 19:41 UTC
