### ISSUE TITLE
Invalid packet issue

### ISSUE THREAD

**Issue by BorbTheBird** [SubnauticaNitrox/Nitrox#2203] opened 2024-11-30 02:43 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

After a session of playing and building a small base I logged off and shut down the server. The next day I started it, connected and loaded into a camera stuck in the lifepod unable to move as well as the hud, inventory and items being completely missing.

### Describe the steps you took to encounter the bug.

Joined a locally hosted server, also tested with different machine.

### Relevant log output

Received invalid, unauthenticated packet: [SetIntroCinematicMode: PlayerId: 1, Mode: COMPLETED, PartnerId: ]

**Comment by Measurity** [comment] 2024-11-30 14:14
Closing as this issue doesn't list all the steps needed to reproduce the issue. The master branch is still in development and not ready for play due to issues like this.

(the log is unrelated to the issue you're seeing, it's related to #2200).

**Closed by Measurity** 2024-11-30 14:14 UTC
Labels: Type: bug, Status: to verify
