### ISSUE TITLE
Fish and items don't spawn for me when my friend hosts.

### ISSUE THREAD

**Issue by TheJimmyWang** [SubnauticaNitrox/Nitrox#840] opened 2019-10-06 17:03 UTC
I'm playing subnautica with steam version and using Himatchi to connect to my friend.  When I join him, no creatures or items spawn for me.  When I host it, it's the other way around and he can't see items.

**Comment by Jannify** [comment] 2020-01-09 23:01
Will probably be fixed with https://github.com/SubnauticaNitrox/Nitrox/pull/854.

**Comment by Measurity** [comment] 2020-04-08 21:27
Gonna close this for now since we can't consistently reproduce it. Please provide detailed information with the steps you took to get this issue and send the player.log file to us. You can find the log here:
`%AppData%\..\LocalLow\Unknown Worlds\Subnautica\Player.log`

**Closed by Measurity** 2020-04-08 21:27 UTC
