### ISSUE TITLE
Directory Not Found Exception

### ISSUE THREAD

**Issue by AzazelHD** [SubnauticaNitrox/Nitrox#945] opened 2020-03-01 16:20 UTC
I am getting System.IO.DirectoryNotFoundException when trying to play multiplayer from the "Play Game" option of the nitrox launcher. I have Subnautica on Epic Games, and I have already selected the directory where the game is.

Why am I getting this and how can i fix it?

**Comment by Coding-Hen** [comment] 2020-03-01 16:23
Currently there is no fix for Epic games. It will be fixed in the next release
Duplicate of #862

Fixed with #855

**Closed** 2020-03-02 08:35 UTC
Labels: fixed on next release
