### ISSUE TITLE
Please write an informative title describing the bug in a few words

### ISSUE THREAD

**Issue by CordeliaHD** [SubnauticaNitrox/Nitrox#2076] opened 2023-09-16 22:26 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Why can’t I scan some objects like the multi room or else?

**Comment by fbievan** [comment] 2023-09-22 13:51
I see this is your first issue ever, sooo i'm going to say some things about this issue.

1) Set a title (like for example this one: Can't scan certain items)
2) For this specific issue, I would recommend including a Video (because it isn't crashing and is instead a behavior)
3)  Don't phrase your Issue as a question (It says to describe it)
4) Include some steps, so we can actually reproduce and properly deal with the issue


Have a great day! 

Sincerely, 
Evan

**Comment by dartasen** [comment] 2023-09-24 08:08
We can't do anything with this bug report. Notes for next time, please fill out the form correctly. Closing this for now

**Closed by dartasen** 2023-09-24 08:08 UTC
Labels: Type: bug, Status: to verify
