### ISSUE TITLE
Base building does not always sync in real time - building with 2 people incurs material costs on both players

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#1601] opened 2021-09-17 15:49 UTC
### Version
Alpha 1.5.0.1
### Bug
There are two types of problems with building  structures

### Steps to reproduce
If a user partially breaks a structure it is not always synchronized to the others until the reboot or until the user rebuilds or completely removes it. When two players build at the same time by adding materials to the same structure, the players lose any extra materials from their inventory. 

### Other details:
[LOGFILE](https://cdn.lucaservers.com/SUB/09-17.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-17-prev.log)

**Comment by lucafont2** [comment] 2021-09-18 15:23
Please note: if any player has extra resources, for example: the structure requires 5 titanium, and the player has 20 titanium in inventory, this bug causes all 20 titanium to be used

**Comment by codefaux** [comment] 2021-10-03 10:24
Can confirm inventory removal bug, cannot agree with "all 20 titanium [...] used" above -- literally had inventory open on idle player, watched -one- Titanium disappear from inventory every time active player built vertical tube. Will do further testing.

**Comment by codefaux** [comment] 2021-10-04 03:49
Further notes - bug is triggered when player DOES NOT HAVE items required to finish building.

- 2x Titanium in inventory, player A
- 20x Titanium in inventory, player B
- Player A attempts to Build X Compartment, requires 3x Titanium
- As soon as Player A reaches build progress to pull third Titanium, Player B's inventory removes one Titanium per tick while Player A attempts to build


For what it's worth, I figured out why it happens and hacked a fix. This is my first time doing pretty much all of the things involved with doing this (lol) so be nice, but it's PR#1614 (https://github.com/SubnauticaNitrox/Nitrox/pull/1614)
It's only been tested by myself, with a partner, for a while. I'm interested in feedback. If you can't self-compile, I'll consider packaging a Release but it's a 100% YMMV situation and I can't promise forward support.

**Comment by Jannify** [comment] 2022-05-25 17:48
Closing in favor of 1812 and bc this is a combined issue

**Closed by Jannify** 2022-05-25 17:48 UTC

**Comment by Measurity** [comment] 2022-05-26 01:38
Duplicate of #1812
