### ISSUE TITLE
BUG : going through textures of buildings when reconnecting

### ISSUE THREAD

**Issue by stilnat** [SubnauticaNitrox/Nitrox#1232] opened 2020-08-31 20:29 UTC
In Aurora, or in the quarantine enforcement platform, when disconnecting from the server and reconnecting, I went tzice through the textures and got stuck "inside" . I could not get out without dying.

**Comment by Coding-Hen** [comment] 2020-10-03 20:03
Closing as duplicate of #624

**Closed by Coding-Hen** 2020-10-03 20:03 UTC
