### ISSUE TITLE
[Base] Bioreactor glitches out when rejoining server.

### ISSUE THREAD

**Issue by lazackna** [SubnauticaNitrox/Nitrox#1521] opened 2021-07-11 08:45 UTC
### Version

1.4.0.0

### Bug

Was playing on a server with friends and we made seperate bases. I build a bioreactor for more power. I had to rejoin because of a visual glitch and when i joined back the bioreactor was unusable.

### Expected

When you build a bioreactor and leave the server and join back in. The bioreactor is unusable.

### Steps to reproduce

1. Build a bioreactor.
2. Leave the server.
3. Rejoin server.
4. The bioreactor will now not work. You will have to deconstruct it and rebuild it.

### Other details:

When rejoining the bioreactor looses all it's contents.

**Comment by Measurity** [comment] 2021-07-11 08:51
Thanks for reporting it but it is a known issue with a common underlying cause. To fix it we need to further implement base sync. For now we recommend using solar panels only. Duplicate of #1400

**Closed by Measurity** 2021-07-11 08:51 UTC
