### ISSUE TITLE
Aurora

### ISSUE THREAD

**Issue by trizmorrow** [SubnauticaNitrox/Nitrox#1020] opened 2020-04-05 13:36 UTC
In my Subnautica Nitrox world, the aurora has exploded 4 times, causing me to go back to it multiple times.

**Comment by Measurity** [comment] 2020-04-05 14:00
Known issue. We aren't saving the event timer yet that triggers this explosion.

Duplicate of #499

**Closed by Measurity** 2020-04-05 14:00 UTC
