### ISSUE TITLE
Cannot inject NitroxPatcher.dll

### ISSUE THREAD

**Issue by TheDarknessz0rz** [SubnauticaNitrox/Nitrox#261] opened 2018-07-17 02:25 UTC
![image](https://user-images.githubusercontent.com/11143072/42793122-4b172b70-893e-11e8-9e7f-966e114b1da5.png)

This also occurs with debugging enabled.
Windows 10 Professional.

1>------ Build started: Project: Lidgren.Network, Configuration: Release Any CPU ------
2>------ Build started: Project: NitroxReloader, Configuration: Release Any CPU ------
3>------ Build started: Project: Harmony, Configuration: Release Any CPU ------
3>  Harmony -> C:\Users\darkness\Desktop\subnautica\Nitrox\Harmony\Harmony\bin\Release\0Harmony.dll
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3267: The primary reference "Microsoft.CSharp", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v3.5". To resolve this problem, either remove the reference "Microsoft.CSharp" or retarget your application to a framework version which contains "Microsoft.CSharp".
1>C:\Users\darkness\Desktop\subnautica\Nitrox\lidgren-network-gen3\Lidgren.Network\NetPeer.Internal.cs(148,28,148,29): warning CS0168: The variable 'e' is declared but never used
1>  Lidgren.Network -> C:\Users\darkness\Desktop\subnautica\Nitrox\lidgren-network-gen3\Lidgren.Network\bin\Release\Lidgren.Network.dll
2>  NitroxReloader -> C:\Users\darkness\Desktop\subnautica\Nitrox\bin\Release\NitroxReloader.dll
4>------ Build started: Project: NitroxModel, Configuration: Release Any CPU ------
4>  NitroxModel -> C:\Users\darkness\Desktop\subnautica\Nitrox\bin\Release\NitroxModel.dll
5>------ Build started: Project: NitroxClient, Configuration: Release Any CPU ------
6>------ Build started: Project: NitroxServer, Configuration: Release Any CPU ------
5>C:\Users\darkness\Desktop\subnautica\Nitrox\NitroxClient\GameLogic\Spawning\DefaultEntitySpawner.cs(15,47,15,113): warning CS0618: 'PrefabDatabase.TryGetPrefab(string, out GameObject)' is obsolete: 'Prefer using GetPrefabAsync'
5>  NitroxClient -> C:\Users\darkness\Desktop\subnautica\Nitrox\bin\Release\NitroxClient.dll
7>------ Build started: Project: NitroxPatcher, Configuration: Release Any CPU ------
8>------ Build started: Project: ClientTester, Configuration: Release Any CPU ------
8>  ClientTester -> C:\Users\darkness\Desktop\subnautica\Nitrox\ClientTester\bin\Release\ClientTester.exe
6>C:\Users\darkness\Desktop\subnautica\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs(79,42,79,44): warning CS0168: The variable 'ex' is declared but never used
6>  NitroxServer -> C:\Users\darkness\Desktop\subnautica\Nitrox\NitroxServer\bin\Release\NitroxServer.exe
7>  NitroxPatcher -> C:\Users\darkness\Desktop\subnautica\Nitrox\bin\Release\NitroxPatcher.dll
9>------ Build started: Project: NitroxTest, Configuration: Release Any CPU ------
9>  NitroxTest -> C:\Users\darkness\Desktop\subnautica\Nitrox\NitroxTest\bin\Release\NitroxTest.dll
========== Build: 9 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by MarijnS95** [comment] 2018-07-17 03:47
Duplicate of #227, #211 

In short, newer versions of dnSpy seem to be unable to recompile just the method that's being edited, and instead attempt to recompile the entire class. Just remove the conflicting attributes and it'll be good.

**Closed** 2018-07-17 04:06 UTC
