### ISSUE TITLE
Items and mobs not spawning

### ISSUE THREAD

**Issue by DanX100** [SubnauticaNitrox/Nitrox#188] opened 2018-03-05 16:53 UTC
Nothing appears in the world, neither thing or mob. There are only 3 fish at the beginning of the game, and above the capsule in the air hanging birds.

**Comment by Kosiak** [comment] 2018-03-06 01:21
Can't confirm. On my side working perfect. Last build. 
![untitled](https://user-images.githubusercontent.com/791788/37008995-b7d1ff44-20dc-11e8-9622-d55db957b151.png)

**Comment by fbermudezgit** [comment] 2018-03-06 06:42
I have the same problem, can someone help?

**Comment by Alberto247** [comment] 2018-03-06 06:43
Check for errors in both the logs of the game and the console of the server.

**Comment by Legired** [comment] 2018-03-06 06:49
Hello guys,

i have the same problem, in output_log.txt, i got this : 

> IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00244>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>

> 

my output_log have 601077 lines

**Comment by MarijnS95** [comment] 2018-03-06 06:59
Please all make sure to compile the latest master branch, and test again. We've made a ton of changes and fixes in the past few days.

Then, make sure to include server log lines: that's where most of the spawning happens.

@legired you are initializing the mod at the wrong time.

**Comment by DanX100** [comment] 2018-03-06 09:17
![image](https://user-images.githubusercontent.com/22075012/37023278-30773184-2147-11e8-92bb-7fc8a1fc5afc.png)
![image](https://user-images.githubusercontent.com/22075012/37023293-3f74ea64-2147-11e8-8c79-6bc2122d8eb6.png)
nothing. only this and that's all.
logs
`(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00244>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>

 
(Filename:  Line: -1)

LightmappedPrefabs all loaded, maybe starting intro vignette frame 3652
 
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 7 Unused Serialized files (Serialized files now loaded: 2)

Unloading 3713 unused Assets to reduce memory usage. Loaded Objects now: 71871.
Total: 473.586121 ms (FindLiveObjects: 11.557948 ms CreateObjectMapping: 10.573278 ms MarkObjects: 447.617950 ms  DeleteObjects: 3.836349 ms)

--- PerformGarbageAndAssetCollectionAsync: GC Time 84.402 Asset GC Time 487.7078
 
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[Nitrox] D: Freezing escape pod rigidbody
IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00244>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>
`
game build 59783
nitrox latest

**Comment by MarijnS95** [comment] 2018-03-06 09:23
@danx100 same for you: you are initializing the mod too late.

**Comment by DanX100** [comment] 2018-03-06 09:24
```
[AbsoluteEntityCell Position: -144,-48,-352 BatchId: 11,18,10 CellId: 9,7,6 Level: 0 ] [AbsoluteEntityCell Position: -144,-48,-336 BatchId: 11,18,10 CellId: 9,7,7 Level: 0 ] [AbsoluteEntityCell Position: -144,-48,-320 BatchId: 11,18,10 CellId: 9,7,8 Level: 0 ] [AbsoluteEntityCell Position: -144,-48,-304 BatchId: 11,18,10 CellId: 9,7,9 Level: 0 ] | PlayerId: 74d21fc9-de35-44dc-a653-f01f9a79aa8d] System.InvalidOperationException: Could not locate subnautica root
   в NitroxServer.Serialization.BatchCellsParser.ParseFile(Int3 batchId, String pathPrefix, String suffix, List`1 spawnPoints) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Serialization\BatchCellsParser.cs:строка 60
   в NitroxServer.Serialization.BatchCellsParser.ParseBatchData(Int3 batchId) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Serialization\BatchCellsParser.cs:строка 39
   в NitroxServer.GameLogic.Entities.Spawning.BatchEntitySpawner.LoadUnspawnedEntities(Int3 batchId) в C:\Users\DanX\Documents\Nitrox\NitroxServer\GameLogic\Entities\Spawning\BatchEntitySpawner.cs:строка 47
   в NitroxServer.GameLogic.Entities.EntityManager.LoadUnspawnedEntities(AbsoluteEntityCell[] cells) в C:\Users\DanX\Documents\Nitrox\NitroxServer\GameLogic\Entities\EntityManager.cs:строка 58
   в NitroxServer.GameLogic.Entities.EntityManager.GetVisibleEntities(AbsoluteEntityCell[] cells) в C:\Users\DanX\Documents\Nitrox\NitroxServer\GameLogic\Entities\EntityManager.cs:строка 22
   в NitroxServer.Communication.Packets.Processors.CellVisibilityChangedProcessor.SendNewlyVisibleEntities(Player player, AbsoluteEntityCell[] visibleCells) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\Packets\Processors\CellVisibilityChangedProcessor.cs:строка 40
   в NitroxServer.Communication.Packets.Processors.CellVisibilityChangedProcessor.Process(CellVisibilityChanged packet, Player player) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\Packets\Processors\CellVisibilityChangedProcessor.cs:строка 30
   в NitroxServer.Communication.Packets.Processors.Abstract.AuthenticatedPacketProcessor`1.ProcessPacket(Packet packet, IProcessorContext player) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\Packets\Processors\Abstract\AuthenticatedPacketProcessor.cs:строка 10
   в NitroxServer.Communication.Packets.PacketHandler.ProcessAuthenticated(Packet packet, Player player) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:строка 65
   в NitroxServer.Communication.Packets.PacketHandler.Process(Packet packet, Connection connection) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:строка 56
   в NitroxServer.Communication.TcpServer.DataReceived(IAsyncResult ar) в C:\Users\DanX\Documents\Nitrox\NitroxServer\Communication\TcpServer.cs:строка 53
[Nitrox] I: No data found from socket, disconnecting
[Nitrox] I: Triggering event type PDA at time 2114000,47383923 with param Story_AuroraWarning2
```
from server

**Comment by DanX100** [comment] 2018-03-06 09:25
@MarijnS95 how can i fix it?

**Comment by DanX100** [comment] 2018-03-06 12:29
okay, i fixed it.
problem was in another folder of the game. i changed folders in server and mobs and loot spawned

**Comment by mhrivera** [comment] 2018-03-06 14:23
DanX100 what were the steps you followed to solve the problems

**Comment by fbermudezgit** [comment] 2018-03-06 14:24
Danx100, you posted the same images that i was about to post.
Can you tell me what folders you modiffied?

**Comment by DanX100** [comment] 2018-03-06 15:40
okay
I modified 2 files: Nitrox server/Serialization/BatchCellsParser.cs and ResoursesAssetsParser.cs
in first file i edited this part of code:
```
        public void ParseFile(Int3 batchId, string pathPrefix, string suffix, List<EntitySpawnPoint> spawnPoints)
        {
            Optional<string> subnauticaPath = SteamHelper.FindSubnauticaPath();

            if (subnauticaPath.IsEmpty())
            {
                throw new InvalidOperationException("Could not locate subnautica root");
            }

            string path = Path.Combine(subnauticaPath.Get(), "SNUnmanagedData/Build18");
            string fileName = Path.Combine(path, pathPrefix + "batch-cells-" + batchId.x + "-" + batchId.y + "-" + batchId.z + "-" + suffix + ".bin");
```
change "Optional<string> subnauticaPath = SteamHelper.FindSubnauticaPath();" to "string subnauticaPath = "C:/Games/Subnautica v59783/";", delete this:
```
            if (subnauticaPath.IsEmpty())
            {
                throw new InvalidOperationException("Could not locate subnautica root");
            }
```
and change "string path = Path.Combine(subnauticaPath.Get(), "SNUnmanagedData/Build18");" to "string path = Path.Combine(subnauticaPath, "SNUnmanagedData/Build18");"

in second file i changed:
```
        private static string FindPath()
        {
            Optional<string> steamPath = SteamHelper.FindSubnauticaPath();

            string gameResourcesPath = "";

            if (!steamPath.IsEmpty())
            {
                gameResourcesPath = Path.Combine(steamPath.Get(), "Subnautica_Data/resources.assets");
            }

            if (File.Exists(gameResourcesPath))
            {
                return gameResourcesPath;
            }
            else if (File.Exists("../resources.assets"))
            {
                return Path.GetFullPath("../resources.assets");
            }
            else if (File.Exists("resources.assets"))
            {
                return Path.GetFullPath("resources.assets");
            }
            else
            {
                throw new FileNotFoundException("Make sure resources.assets is in current or parent directory and readable.");
            }
        }
```
delete:
```
           if (!steamPath.IsEmpty())
            {
                gameResourcesPath = Path.Combine(steamPath.Get(), "Subnautica_Data/resources.assets");
            }
```
and
```
            }
            else if (File.Exists("../resources.assets"))
            {
                return Path.GetFullPath("../resources.assets");
            }
            else if (File.Exists("resources.assets"))
            {
                return Path.GetFullPath("resources.assets");
            }
```
and change "string gameResourcesPath = "";" to "string gameResourcesPath = "C:/Games/Subnautica v59783/Subnautica_Data/resources.assets";"
of course, you need to change my game folder to your game folder!
and... tadaa! mobs and loot are spawning!
but now not working game save and i try to fix it...

**Comment by Legired** [comment] 2018-03-06 18:30
@MarijnS95 i got this after change : 

> (Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: 8193553b-b829-404c-8fa0-ae0f80bfaef0
[Nitrox] E: Expected to simulate an unknown entity: 8193553b-b829-404c-8fa0-ae0f80bfaef0
[Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: 83415770-8d0e-4b47-b5e6-1950cbb1477d
[Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: a93b4c71-676d-4316-9bc9-8e7219aa0a89
[Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: d44171d1-91eb-42c9-9b4a-209d9c303b04
No filename for prefab a33606a0-b708-4629-a2e2-f14de06f8032 in database containing 3316 entries

>

**Comment by Alberto247** [comment] 2018-03-06 18:43
Are you using an original version of the game? Because from the code you had to edit looks like you aren't.
However, the first two types of errors(entity already spawned and expected to simulate an unknown entity) are errors which happen to me too, but my game can load entities despite them. I've never seen the last one(no filename for prefab).
Can you include the server log?

**Comment by Legired** [comment] 2018-03-06 18:47
Hello, 

yes i got the original version of the game (it's another guy who change the directory)

here the server log : 

> [Nitrox] I: New client connected
[Nitrox] I: Providing session policies...
[Nitrox] I: Processing reservation request...
[Nitrox] I: Reservation processed successfully: ReservationState: Reserved - ReservationKey: 6da1f7c0-dcd0-437f-b980-ed8e4a8cf5c9...
[Nitrox] D: Batch 12,19,12 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 12,19,12
[Nitrox] D: Batch 13,19,12 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 13,19,12
[Nitrox] D: Batch 12,18,12 not parsed yet; parsing...
[Nitrox] D: Loaded 3629 entity-spawn-points for batch 12,18,12
[Nitrox] D: Batch 13,18,12 not parsed yet; parsing...
[Nitrox] D: Loaded 2817 entity-spawn-points for batch 13,18,12

>

**Comment by mhrivera** [comment] 2018-03-07 02:43
DanX100 the solution that you give this perfect only that does not catch the sulfur the fish that explode do not come out and there is no sulfur you know how to solve this problem ????

**Comment by Ameo-Koradi** [comment] 2018-03-07 07:09
Confirmed, sulfure and some mobs don't spawn (for ex.: the mob that takes scraps in mouth)

**Comment by DanX100** [comment] 2018-03-07 13:42
@Ameo-Koradi @mhrivera yes, i see them. Some mobs and loot not spawning.
I found a simpler solution. you need to setup or copy game in steamapps folder f create appmanifest for this game and any manipulations with the mod not necessary to carry out... but... is not fix spawning

**Comment by DanX100** [comment] 2018-03-07 13:43
and yes. i use "pirate" version of the game)

**Comment by MarijnS95** [comment] 2018-03-07 13:48
This is a known issue. For the time being, the server cannot properly run on a machine without Steam installed. This'll be fixed in the future, once we introduce config files for the server.

Besides, we do not support nor condone the use of a pirated game.

**Closed by MarijnS95** 2018-03-07 13:48 UTC

**Comment by Sajgoniarz** [comment] 2018-12-15 08:17
All DanX100 changes can be simple tweaked to return hardcoded subnautica path from SteamHelper, but in my case its not fixing spawn issue.

**Comment by dexter74** [comment] 2018-12-17 22:55
Can you help:


        private static string FindPath()
        {
            List<string> errors = new List<string>();
            Optional<string> subnauticaPath = GameInstallationFinder.Instance.FindGame(errors);
            if (subnauticaPath.IsEmpty())
            {
                Log.Info($"Could not locate Subnautica installation directory: {Environment.NewLine}{string.Join(Environment.NewLine, errors)}");
            }

**Comment by dexter74** [comment] 2018-12-17 23:50
need update tutorial

**Comment by Sajgoniarz** [comment] 2018-12-18 05:36
Update tutorial for?

**Comment by dexter74** [comment] 2018-12-18 05:53
edit file

**Comment by Sajgoniarz** [comment] 2018-12-18 08:31
@dexter74 
1. You were warned, that you should not use Nitrox until you are not a developer
2. Issue is related to old implementation, and now mostly works.
3. You should just put Subnautica path in path.txt file in server directory.

**Comment by dexter74** [comment] 2018-12-18 20:30
Need Fix please.

**Comment by Sajgoniarz** [comment] 2018-12-18 20:31
Its known issue to devs, they are working hard to find out whats wrong with it.

**Comment by dexter74** [comment] 2018-12-18 20:33
Nice .
