### ISSUE TITLE
Games takes Loading Multiplayer forever

### ISSUE THREAD

**Issue by Lostblue** [SubnauticaNitrox/Nitrox#815] opened 2019-06-02 21:32 UTC
When joining on my own server after a break, I just can't pass the stage of "Loading Multiplayer". 

On the server console, I can read "[NM] DataReceived: Bad!".

When I go to the logs inside the game folder (~/Subnautica/Subnautica_Data/output_log.txt), I can see the following error ("Lostblue" is myself) :
[23:20:08 INFO]: Updating session stage from 'SessionReserved' to 'SessionJoined' for 'Lostblue'
[NM] SocketReceiveThread error: System.Runtime.Serialization.SerializationException: Field "AssignedEscapePodGuid" not found in class NitroxModel.Packets.InitialPlayerSync
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadTypeMetadata (System.IO.BinaryReader reader, Boolean isRuntimeObject, Boolean hasTypeInfo) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObjectInstance (System.IO.BinaryReader reader, Boolean isRuntimeObject, Boolean hasTypeInfo, System.Int64& objectId, System.Object& value, System.Runtime.Serialization.SerializationInfo& info) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObject (BinaryElement element, System.IO.BinaryReader reader, System.Int64& objectId, System.Object& value, System.Runtime.Serialization.SerializationInfo& info) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObject (BinaryElement element, System.IO.BinaryReader reader, System.Int64& objectId, System.Object& value, System.Runtime.Serialization.SerializationInfo& info) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObject (BinaryElement element, System.IO.BinaryReader reader, System.Int64& objectId, System.Object& value, System.Runtime.Serialization.SerializationInfo& info) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadNextObject (BinaryElement element, System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ReadObjectGraph (BinaryElement elem, System.IO.BinaryReader reader, Boolean readHeaders, System.Object& result, System.Runtime.Remoting.Messaging.Header[]& headers) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.NoCheckDeserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in <filename unknown>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in <filename unknown>:0 
  at NitroxModel.Packets.Packet.Deserialize (System.Byte[] data) [0x00000] in <filename unknown>:0 
  at NitroxClient.Communication.NetworkingLayer.LiteNetLib.LiteNetLibClient.OnPacketReceived (NitroxModel.Packets.WrapperPacket wrapperPacket, LiteNetLib.NetPeer peer) [0x00000] in <filename unknown>:0 
  at LiteNetLib.Utils.NetPacketProcessor+<>c__DisplayClass29_0`2[NitroxModel.Packets.WrapperPacket,LiteNetLib.NetPeer].<SubscribeReusable>b__0 (LiteNetLib.Utils.NetDataReader reader, System.Object userData) [0x00000] in <filename unknown>:0 
  at LiteNetLib.Utils.NetPacketProcessor.ReadPacket (LiteNetLib.Utils.NetDataReader reader, System.Object userData) [0x00000] in <filename unknown>:0 
  at LiteNetLib.Utils.NetPacketProcessor.ReadAllPackets (LiteNetLib.Utils.NetDataReader reader, System.Object userData) [0x00000] in <filename unknown>:0 
  at NitroxClient.Communication.NetworkingLayer.LiteNetLib.LiteNetLibClient.ReceivedNetworkData (LiteNetLib.NetPeer peer, LiteNetLib.Utils.NetDataReader reader, DeliveryMethod deliveryMethod) [0x00000] in <filename unknown>:0 
  at LiteNetLib.EventBasedNetListener.LiteNetLib.INetEventListener.OnNetworkReceive (LiteNetLib.NetPeer peer, LiteNetLib.NetPacketReader reader, DeliveryMethod deliveryMethod) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.ProcessEvent (LiteNetLib.NetEvent evt) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.CreateEvent (EType type, LiteNetLib.NetPeer peer, System.Net.IPEndPoint remoteEndPoint, SocketError errorCode, Int32 latency, DisconnectReason disconnectReason, LiteNetLib.ConnectionRequest connectionRequest, DeliveryMethod deliveryMethod, LiteNetLib.NetPacket readerSource) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.ReceiveFromPeer (LiteNetLib.NetPacket packet, System.Net.IPEndPoint remoteEndPoint) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetPeer.AddIncomingPacket (LiteNetLib.NetPacket p) [0x00000] in <filename unknown>:0 
  at LiteNetLib.ReliableChannel.ProcessPacket (LiteNetLib.NetPacket packet) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetPeer.ProcessPacket (LiteNetLib.NetPacket packet) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.DataReceived (System.Byte[] reusableBuffer, Int32 count, System.Net.IPEndPoint remoteEndPoint) [0x00000] in <filename unknown>:0 
  at LiteNetLib.NetManager.LiteNetLib.INetSocketListener.OnMessageReceived (System.Byte[] data, Int32 length, SocketError errorCode, System.Net.IPEndPoint remoteEndPoint) [0x00000] in <filename unknown>:0

**Comment by EnhancedC** [comment] 2019-10-12 12:18
Are you still getting this problem?
because i need a fix and i cant find anything

**Comment by Lostblue** [comment] 2019-10-12 13:21
We've fixed this issue using a decompilation of Nitrox (as many of us are devs.). I don't remember what we had changed since it's a long time ago.
If you are a dev too, we used Reflector / Reflexil. According to logs, the error should be a caller of AssignedEscapePodGuid.
Sorry I can't help you further since we don't play anymore and are waiting further fixes on sync for the Aurora wreckage.

**Comment by Lostblue** [comment] 2019-10-12 13:57
Ok I double checked with my friends. This issue appears when we have different versions of Subnautica.
We just changed to the April 2019 version to solve this issue.

**Comment by Coding-Hen** [comment] 2019-12-30 17:34
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
