### ISSUE TITLE
Base Building not synced and structure deconstructing not saving

### ISSUE THREAD

**Issue by Austin4705** [SubnauticaNitrox/Nitrox#1017] opened 2020-04-04 04:27 UTC
We built a base and then we destroyed some of it and then we saved and left when we rejoined the base was at the old state before we took down some of it so I did the process of tearing some of it down again but it only got torn down for me and when we relogged again the same issue

**Comment by Measurity** [comment] 2020-04-05 12:35
Duplicate of #1003

**Closed by Measurity** 2020-04-05 12:35 UTC
