### ISSUE TITLE
Radio dont play more messages

### ISSUE THREAD

**Issue by KnTz0** [SubnauticaNitrox/Nitrox#1294] opened 2020-11-24 22:54 UTC
### Version
<!-- Nitrox 1.3.0.0 --!>

 ### Bug
<!-- Radio dont play more messages --!>
the first missions played normally, but 2 days later the radio never played any messages again, so we were unable to progress in the history of the game

**Comment by Measurity** [comment] 2020-11-24 23:44
Duplicate of #1124

**Closed by Measurity** 2020-11-24 23:44 UTC
Labels: duplicate
