### ISSUE TITLE
No fish..Nothing!

### ISSUE THREAD

**Issue by FenetreXxMagique** [SubnauticaNitrox/Nitrox#408] opened 2018-12-19 16:15 UTC
Hello, I come here following a problem with the mod :/

I downloaded and installed the latest version from NexusMod.
But I have a problem .. I have no fish anywhere!

Do you have an idea ?

Thank you so much :)

![sans titre-1](https://user-images.githubusercontent.com/37071507/50232583-9e36d880-03b1-11e9-8927-0829e2829490.jpg)

![011](https://user-images.githubusercontent.com/37071507/50232590-a4c55000-03b1-11e9-9abd-68d1e730c0f4.jpg)

**Comment by xkaczors** [comment] 2018-12-19 16:49
As we have already written Sajgoniarz, still working on this, we just have to wait

**Comment by FenetreXxMagique** [comment] 2018-12-19 17:04
Oh, ok sorry :) Thank you !

**Comment by Tibnan** [comment] 2018-12-19 19:08
Well, I have the same problem and I've got only a "Duplicate of #188", but that guide helped nothing...
It's good to know that they are working on it.

**Comment by Sajgoniarz** [comment] 2018-12-20 13:43
Well duplicating issues (and answering for them) is very stressful ;p Please verify issue with lastest version (https://github.com/SubnauticaNitrox/Nitrox/commit/0828c3e1afe46df586ed37948bbfc30525713461). @Sunrunner37 is working hard on it :)

**Comment by Tibnan** [comment] 2018-12-20 13:45
I'm trying to create server logs with the latest version, However, it isn't even responding for the command

**Comment by Sajgoniarz** [comment] 2018-12-20 13:52
'>' is cmd command to redirect output to file. In your case it will be just log without any extension. You can just run it without cmd, and then copy output from window. If you have some problem past screen of your cmd and server directory.

**Comment by Tibnan** [comment] 2018-12-20 13:55
> '>' is cmd command to redirect output to file. In your case it will be just log without any extension. You can just run it without cmd, and then copy output from window. If you have some problem past screen of your cmd and server directory.

So if I just insert the previously mentioned command into cmd, and create a log.txt, then will it copy the output there?

**Comment by Sajgoniarz** [comment] 2018-12-20 13:58
Yes. You must run cmd in server directory. You can do it with shift + rmb in server folder, to open cmd there (in PowerShell it should work the same)

**Comment by Tibnan** [comment] 2018-12-20 14:04
> Yes. You must run cmd in server directory. You can do it with shift + rmb in server folder, to open cmd there (in PowerShell it should work the same)

Eeeh no result?
 
![image](https://user-images.githubusercontent.com/45972570/50289239-853d2e80-0468-11e9-9488-b4667f83e29e.png)

**Comment by trjflash** [comment] 2018-12-20 14:14
It work only with CMD. Witch exe file this will not be working

**Comment by Tibnan** [comment] 2018-12-20 14:20
> It work only with CMD. Witch exe file this will not be working

I have no option to start cmd in the folder..... Well I give up. I hope it gets fixed.

**Comment by Sajgoniarz** [comment] 2018-12-20 14:20
Haha, you must paste it without quotes. Quotes in Powershell turns it into variable, which you want to immediately display :D

**Comment by Tibnan** [comment] 2018-12-20 14:23
> Haha, you must paste it without quotes. Quotes in Powershell turns it into variable, which you want to immediately display, so it wont work, because you are not executing server exe at all ;p

Well...
![image](https://user-images.githubusercontent.com/45972570/50290188-2fb65100-046b-11e9-97e6-1193f09260af.png)

**Comment by Sajgoniarz** [comment] 2018-12-20 14:50
Everything what can help devs is welcome :)

**Comment by Tibnan** [comment] 2018-12-20 14:51
> Everything what can help devs is welcome :)

I'm more than happy to help you.
[log(NitroxServer.exe).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2699286/log.NitroxServer.exe.txt)
[log(Generated_with_PowerShell).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2699287/log.Generated_with_PowerShell.txt)

**Closed** 2019-01-13 19:48 UTC
