### ISSUE TITLE
Bioreactor Problems

### ISSUE THREAD

**Issue by EinLuigi** [SubnauticaNitrox/Nitrox#1404] opened 2021-01-20 09:08 UTC
### Bug

let your friend build a Bioreactor than you see it. It is not 100% finished with constructing

### Expected

That it is constructed

### Other details:
![notfinished-bioreactor-problem-subnautica-nitrox](https://user-images.githubusercontent.com/62796561/105152372-5ee69300-5b07-11eb-9dcb-457d4ab86eee.PNG)

**Comment by Exso12Ecesis** [comment] 2021-01-20 15:09
This is a duplicate of #1400.

**Closed** 2021-05-09 16:33 UTC
Labels: duplicate
