### ISSUE TITLE
Aurora warning patch and random auroraTime persistence

### ISSUE THREAD

**Issue by quimnuss** [SubnauticaNitrox/Nitrox#678] opened 2019-01-28 18:59 UTC
`CreateWorld `gets called by `CreateFreshWorld `and also `LoadFromFile`, and it builds a new `EventTriggerer `which recreates random timers for the aurora events. Here: https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer/Serialization/World/WorldPersistence.cs#L136

Persisting the random `auroraTimer ` will fix this since `serverStartTime `is already persisted.

Additionally, class `AuroraWarnings::Update()` is not patched so the client will trigger the events regardless of the server trigger.

Duplicate of #499
Duplicate of #626

**Comment by quimnuss** [comment] 2019-01-28 19:06
Also, quick temporary fix without changing the persisted data is to remove the randomness.

**Comment by aeppacher** [comment] 2019-01-29 22:21
Duplicate of #626

**Comment by quimnuss** [comment] 2019-01-29 23:47
Correction. The AuroraWarnings Update actually calls Trigger on auroraWarningN StoryGoal which ultimately calls the StoryGoal.Execute() which _is_ patched. These auroraWarning fields seem to be set in the UnityEditor, so I don't know what GoalType they are, which seems important because StoryGoal::Execute handles PDA, Radio and Encyclopedia, but nothing is called there for Story GoalType.

Anyway, what looks certain is that the crashedShipExploder explosion story event is handled on its own monobehaviour.

Another method that needs to be changed is `CrashedShipExploder::Update()`, which is the one actually exploding the aurora. Nitrox takes care of this in the StoryGoal patch and related messages by setting the countdown+explosion time at the moment the explosion packet is received; effectively triggering the explosion at the next frame Update.

**Comment by Coding-Hen** [comment] 2020-04-19 22:44
@Measurity This can be closed

**Closed** 2020-04-20 17:43 UTC
Labels: bug
