### ISSUE TITLE
Please help me. My Subnautica won't launch in the multiplayer window, and it says this

### ISSUE THREAD

**Issue by getnoob-boi** [SubnauticaNitrox/Nitrox#877] opened 2020-01-05 01:47 UTC

**Comment by getnoob-boi** [comment] 2020-01-05 01:49
My subnautica wont launch in the multiplayer window, and all it says is 
![IMG_0209](https://user-images.githubusercontent.com/59519648/71773924-f429e000-2f22-11ea-91bf-88df5b594d64.JPG)

**Comment by Coding-Hen** [comment] 2020-01-05 01:55
Please go to the discord server and look at the mod-fixes channel and use option 1
Duplicate of #862 

Fixed with #855

**Comment by getnoob-boi** [comment] 2020-01-05 03:36
Thx

**Comment by getnoob-boi** [comment] 2020-01-05 03:44
But is there a tutorial of how to do it because I am confused

**Comment by Measurity** [comment] 2020-01-05 16:54
I recommend getting on the Nitrox Discord server because we have information on how to work around this issue.

https://discordapp.com/invite/E8B4X9s

**Closed by Measurity** 2020-01-05 16:54 UTC
