### ISSUE TITLE
Mission stucks

### ISSUE THREAD

**Issue by SKinboy2** [SubnauticaNitrox/Nitrox#1298] opened 2020-11-27 22:15 UTC
Hi I am a fresh user for nitrox and I just encountered this bug where me and my friend no long see the mission's location after we restart the game, and on starting server page we have this(as followed)
![image](https://user-images.githubusercontent.com/39146398/100486890-59239100-3106-11eb-9d5b-ffa81bd74823.png)
Is there anything we can do to fix it?

**Comment by Measurity** [comment] 2020-12-03 12:00
Duplicate of #1092
Fixed in #1225

**Closed by Measurity** 2020-12-03 12:00 UTC
Labels: duplicate
