### ISSUE TITLE
Glitch with the Aurora drive core

### ISSUE THREAD

**Issue by FattyBoi90** [SubnauticaNitrox/Nitrox#1430] opened 2021-03-03 15:53 UTC
I am playing on Nitrox Alpha version 1.4.0.0. Every time I get on the server it says how I need to fix the Aurora in order to stop the radiation. What should happen is I should only have to fix it once and never have to worry about the radiation. It even stopped having radiation but I shit the server down, started it again, and it said I had to go fix the ship and there was radiation.
I have no idea on how to replicate this issue since I've seen no one else with it. But basically I have to fix the Aurora every time I start the server.

**Comment by Coding-Hen** [comment] 2021-03-03 16:35
Duplicate of #693 
This is to do with the leaks/damage points not being synced. Can possibly be solved with the fixleaks in the developer console each time you restar/login

**Closed by Coding-Hen** 2021-03-03 16:35 UTC
