### ISSUE TITLE
A couple of bugs me and a friend found

### ISSUE THREAD

**Issue by 69dababy420** [SubnauticaNitrox/Nitrox#1532] opened 2021-07-20 20:04 UTC
If you fix the Auroras drive core the radion will just come back after rejoining a server
Reapers don't spawn 
If one player turns on the lights in a seamoth the other player can hear it
Some wrecks are very bugged out (Picture for reference)
The moonpool sometimes shows that a player is docked in the moonpool even if they are far away from the moon pool
Sometimes seamoths (And probably other vehicles) sometimes dissapear or break very easily if they hit another seamoth
Creatures and other map objects only spawn when you get very very close
When you rejoin a server all your tools batteries will be charged to 100% 
Fragments respawn when rejoining a server
Crabsnakes are supersized (picture for reference)
Sometimes players seamoths appear in a location where they are not
Sometimes seamoths can be docked on one players side but be undocked and used by another player
Fabricator keeps playing animation and sound when used for the first time when a server is first created
Buildables don't have legs that extend into the ground
Can hear reaper roar in rare occastions but no reapers spawn
https://cdn.discordapp.com/attachments/833024260409917532/867080990509891584/unknown.png
https://cdn.discordapp.com/attachments/833024260409917532/867100088962777138/unknown.png
https://cdn.discordapp.com/attachments/833024260409917532/867115796727988264/unknown.png
https://cdn.discordapp.com/attachments/833024260409917532/867117152943341578/unknown.png
https://cdn.discordapp.com/attachments/833024260409917532/867095841440792616/unknown.png
https://cdn.discordapp.com/attachments/833024260409917532/867084382203281408/unknown.png

This would take awhile and just clutter everything up if i wrote it all in that other format.

**Comment by Measurity** [comment] 2021-07-20 20:55
Radiation is not synced
**Known issue** https://github.com/SubnauticaNitrox/Nitrox/issues/1454

Reapers don't spawn
**work in progress, not a bug.**

If one player turns on the lights in a seamoth the other player can hear it
**Fixed next release**

Some wrecks are very bugged out (Picture for reference)
**Known issue: https://github.com/SubnauticaNitrox/Nitrox/issues/1468**

Fragments respawn when rejoining a server
Known issue: https://github.com/SubnauticaNitrox/Nitrox/issues/1252

Fabricator keeps playing animation and sound when used for the first time when a server is first created
**Sound is disabled next release, we will fix other issues with it, we know about these issues.**

When you rejoin a server all your tools batteries will be charged to 100%
**Known issue**: https://github.com/SubnauticaNitrox/Nitrox/issues/1391

Creatures and other map objects only spawn when you get very very close
**We have limited range where server spawns objects. We'll look into increasing this but it has a high performance impact.**

Seamoth breaks easily
**Known issue** https://github.com/SubnauticaNitrox/Nitrox/issues/1359

**Bases, and what is attached to them (i.e. moonpool) are a work in progress. We know about the issues.**

I'm closing this for now because many issues are already known, related to a WIP feature or are (relatively) very minor issues. If you have a bug that we don't know about then create a new issue for each of them please.

**Closed by Measurity** 2021-07-20 20:55 UTC
Labels: duplicate, fixed on next release
