### ISSUE TITLE
dnSpy does not edit Assembly-CSharp.dll

### ISSUE THREAD

**Issue by Egor179** [SubnauticaNitrox/Nitrox#227] opened 2018-06-25 06:16 UTC
At compilation produces a lot of errors, did everything the same as always.
https://c.radikal.ru/c35/1806/5e/96497e52d84f.png

**Comment by quimnuss** [comment] 2018-06-27 22:34
There's the exact same issue like 6 issues below this one. Please read what's there before posting.

https://github.com/SubnauticaNitrox/Nitrox/issues/211

**Comment by AlexejheroYTB** [comment] 2018-06-28 08:22
Duplicate of #221

**Comment by AlexejheroYTB** [comment] 2018-06-28 08:23
(Added comment because `Duplicate of #` is a GitHub keyword)

**Comment by quimnuss** [comment] 2018-06-28 08:36
I guess you meant 211 ?

Duplicate of #211

**Comment by quimnuss** [comment] 2018-06-28 08:38
Duplicate of #211

**Closed** 2018-06-29 08:36 UTC
