### ISSUE TITLE
Bases and inventories not being saved on exit

### ISSUE THREAD

**Issue by EnhancedC** [SubnauticaNitrox/Nitrox#967] opened 2020-03-15 14:20 UTC
when ever i leave the game the all of the moduals  for the base get put to 92% construction
![image](https://user-images.githubusercontent.com/42080745/76703229-116bef00-66c8-11ea-9083-2c6a1b31d348.png)
and previous things i have constructed in them are stuck and i can deconstruct them

**Comment by NitroxPower** [comment] 2020-03-16 10:15
#691  This is the bugs for an older version. I assume they are simular since not much have changed from them

**Comment by EnhancedC** [comment] 2020-03-18 21:22
> #691 This is the bugs for an older version. I assume they are simular since not much have changed from then

i have the latest version

**Comment by LordOfTheGulls** [comment] 2020-03-19 21:40
I have the latest version too, and I can confirm that the server doesn't save player's inventory.

**Comment by shall987** [comment] 2020-03-21 12:23
somebody discovered how it does??
i have the latest version on the launcher and every time that i start a server my itens dissapear but my constructions and everything don't
Can someone help me?

**Comment by TheClockTwister** [comment] 2020-03-28 01:05
The partially finished constructions bug can now be avoided using [this advice](https://github.com/SubnauticaNitrox/Nitrox/issues/1000#issuecomment-605371622)

**Comment by erios567** [comment] 2020-03-30 23:33
> somebody discovered how it does??
> i have the latest version on the launcher and every time that i start a server my itens dissapear but my constructions and everything don't
> Can someone help me?

You can avoid that Problem by closing the server manually before anybody leaves the server. Everyone has to stay in the server until he is getting kicked. 
I describe this in a bit more detail in #1003

**Comment by Sunrunner37** [comment] 2020-04-04 03:36
tracked in https://github.com/SubnauticaNitrox/Nitrox/issues/951

**Closed by Sunrunner37** 2020-04-04 03:36 UTC
