### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by theonetoday** [SubnauticaNitrox/Nitrox#710] opened 2019-02-03 03:37 UTC
I and another friend are able to connect to and play on the server. One other friend cannot. It gets stuck on the loading multiplayer screen. 
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2825148/output_log.txt)
[nitrox-2019-02-01.1.log](https://github.com/SubnauticaNitrox/Nitrox/files/2825149/nitrox-2019-02-01.1.log)

**Comment by NitroxPower** [comment] 2019-02-03 05:52
this issue has been resolved in #700 close this issue

**Comment by theonetoday** [comment] 2019-02-03 06:01
> this issue has been resolved in #700 close this issue

I was told to make a new issue for mine in the same issue

**Comment by NitroxPower** [comment] 2019-02-03 06:05
But i did report exacly the same issue and with Asimpson i gave him the output log and he fixed it

**Comment by theonetoday** [comment] 2019-02-03 06:05
and he told me to make a new one

**Comment by NitroxPower** [comment] 2019-02-03 06:14
Yes i see now there are more instances so that happens

**Comment by SFRacing** [comment] 2019-07-17 16:12
A friend and i played together for 3 days. today we got infinite loading screens too.
Log file: 
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3402791/output_log.txt)

I hope there is a fix for this ;(

**Comment by Coding-Hen** [comment] 2019-12-30 17:36
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
