### ISSUE TITLE
Disappear items in battery charger after server restart

### ISSUE THREAD

**Issue by Rezigar** [SubnauticaNitrox/Nitrox#1549] opened 2021-07-27 17:18 UTC
### Version
Nitrox_1.5.0.1

### Bug
Disappear items in battery charger and upgrades in seamoth after server restart. Remains installed last one.

**Comment by Measurity** [comment] 2021-07-27 17:19
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/1406

**Closed by Measurity** 2021-07-27 17:19 UTC
