### ISSUE TITLE
Scanner Room not synced

### ISSUE THREAD

**Issue by BrightenedDay** [SubnauticaNitrox/Nitrox#2109] opened 2024-01-13 19:37 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

The camera drones, and the scanner room itself isnt synced between players.
Also the camera drones don't seem to be saving their positions. (Basically gets reset every time client rejoins as its not synced).

**Comment by Measurity** [comment] 2024-09-06 16:23
Duplicate of #2109

**Closed by Measurity** 2024-09-06 16:23 UTC
Labels: Type: bug, Status: to verify, Area: bases
