### ISSUE TITLE
The Portal at the Cannon Island Doest Exist

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#697] opened 2019-02-01 19:40 UTC
For me its visible but my friend cant see the portal.... And it just dissapeared after i used the portal

**Comment by Jannify** [comment] 2020-06-01 14:57
Is this still valid?

**Comment by dartasen** [comment] 2020-11-23 21:27
Cannot reproduce the issue, also it's quite old so i'm closing it

**Closed by dartasen** 2020-11-23 21:27 UTC
