### ISSUE TITLE
System.IO.DirectoryNotFoundExeption

### ISSUE THREAD

**Issue by digui14** [SubnauticaNitrox/Nitrox#885] opened 2020-01-11 00:18 UTC
I know u can "Fix" this bug by copying the mono file into the Subnautica_Data file, but then the no menu bug appears for me , and i know that u can fix that bug by downgrading the version of subnautica.. but when i do that the first fix of the System.Io.Directory wont work and it wont find the file

**Comment by OfficialZygorg** [comment] 2020-01-11 17:46
f

**Comment by T1G3Rx** [comment] 2020-01-13 14:45
how to fix it ?

**Comment by KoromaruKoruko** [comment] 2020-01-13 14:49
is this the one about the missing discord-rpc.dll file?

**Comment by T1G3Rx** [comment] 2020-01-13 15:08
yes my version of the game from epic game

**Comment by T1G3Rx** [comment] 2020-01-13 15:12
![image](https://user-images.githubusercontent.com/39460577/72266820-2d9fd100-3630-11ea-8853-786a9d1cab7f.png)

**Comment by Alanjurowce** [comment] 2020-01-16 17:41
I have the same and I idk why the discord thing is in there maybe it is the problem

**Comment by Coding-Hen** [comment] 2020-01-16 17:47
This has been fixed on the master #855

**Comment by BugsReporter** [comment] 2020-01-21 15:27
I really need a fix tutorial. Please, I want it to play with my sister and when I Start a server on Himachi and on Nitrox launcher and My sister was joined, then when I clicked on Play Multiplayer Then the bug showed up and I was thinking: Where is that Mono folder?

I tried everything and then I just created a Mono folder in Subnautica_Data and in the folder, I created a file named (I thing) discord-rpc.dll and then it has got a bug and then it crashed

Can you please tell me the tutorial how to fix it?

Or how to add that MONO FOLDER AND THAT DISCORD-RPC.DLL FILE?

Thank u.

**Comment by Measurity** [comment] 2020-01-22 21:07
@BugsReporter I recommend waiting for next release which will be in about ~3 weeks. We're still in the progress of improving the experience even though we have fixed this specific issue already.

Gonna close this issue too because it's a duplicate of #856

**Closed by Measurity** 2020-01-22 21:07 UTC
Labels: fixed on next release

**Comment by BugsReporter** [comment] 2020-02-14 18:28
Thank you

Dne st 22. led 2020 22:07 uživatel Measurity <notifications@github.com>
napsal:
