### ISSUE TITLE
Keep getting "Lost connection to game"

### ISSUE THREAD

**Issue by Gracethelittleartist1010** [SubnauticaNitrox/Nitrox#1335] opened 2020-12-21 07:23 UTC
### Version
1.3.0.0

### Bug
 I set up everything with my friend (subnautica add the right ip address, nitrox start server, hamachi (we both did the ping thing successfully), etc.) but we keep getting the error "lost connection to game server" a few seconds after we load into the game and when we press "ok" the game crashes. We never see each other ingame. When I go to the nitrox console since I'm hosting, I see the message "cannot send packet to a closed connection". I tried restarting the server and the game and hamachi, but it's still happening.

### Expected
in game prompt saying "Lost Connection to Game Server" with a button "Ok", the game then closes after pressing ok

### Steps to reproduce
start connection on hamachi, connect with friend, launch subnautica with nitrox, start server with nitrox, copy ipv4 address on hamachi, paste in subnautica add server input, click join, choose username and color, wait for game to load, prompt shows after game loads

### Other details:
player log here: https://drive.google.com/file/d/1Tq7fHKeqaMcf0kTcVH3D4bbPODAnkFvV/view?usp=sharing

**Comment by Jannify** [comment] 2021-01-10 19:46
This is probably caused by the (Hamachi) connection and not by Nitrox. Pls visit our discord for help. Closing this for now.

**Closed by Jannify** 2021-01-10 19:46 UTC
