### ISSUE TITLE
Can't see the main menu!

### ISSUE THREAD

**Issue by 1PepsiMan1** [SubnauticaNitrox/Nitrox#939] opened 2020-02-28 18:52 UTC
So when I launch the game with nitrox, I can't see the main menu. In singleplayer, I can see it, but in multiplayer, the game launches, but I can't see the main menu. I tried reinstalling nitrox, I tried older versions of nitrox, nothing works. Any help? If any more info is required, tell me and I'll provide.

**Comment by Coding-Hen** [comment] 2020-02-28 20:15
Thanks for reporting but this has already been reported. If you are using steam then head to the discord server where you can find a pinned tab in the help channel for resolving this issue with a downgrade.
Duplicate of #859
Fixed in commit 1759c5c

**Comment by 1PepsiMan1** [comment] 2020-02-28 20:23
But I am using Epic Games launcher. Not steam. I'll check the discord pin but will it work the same for Epic?

**Comment by Coding-Hen** [comment] 2020-02-28 20:25
> 
> 
> But I am using Epic Games launcher. Not steam. I'll check the discord pin but will it work the same for Epic?

Currently no but as mentioned in the duplicate issue this is fixed for the upcoming release. Watch the discord, you will be notified of when the release is out.

**Comment by 1PepsiMan1** [comment] 2020-02-28 20:26
Okay, thank you.

**Closed** 2020-02-28 21:03 UTC
