### ISSUE TITLE
Infinite loading multiplayer

### ISSUE THREAD

**Issue by Damply** [SubnauticaNitrox/Nitrox#858] opened 2019-11-24 02:23 UTC
I've tried every other fix from other issues here, i've asked in discord and searched everywhere on google. The log does not show any serious errors from i can see. [Here is the log output](https://pastr.io/raw/RzJYLy)

**Comment by alepiumetti** [comment] 2019-11-24 05:47
Same problem

**Comment by egor-png** [comment] 2019-11-24 10:47
+

**Comment by egor-png** [comment] 2019-11-24 10:49
+

**Comment by egor-png** [comment] 2019-11-24 10:49
таже фигня

**Comment by Damply** [comment] 2019-11-24 23:58
Anyone know a fix? Seems like no one has any clue whats causing it

**Comment by Andrewbandrew05** [comment] 2019-11-25 02:13
This is a known problem which began around the begining of November. The dev teams working on it and hopefully will get it fixed soon

**Comment by killzoms** [comment] 2019-11-25 09:40
@Damply what does the server log say?

**Comment by Kodi4444** [comment] 2019-12-14 06:58
the only way I was able to fix it is reinstalling subnautica but after that nitrox stopped working,

**Comment by Coding-Hen** [comment] 2019-12-30 17:30
Duplicate of #412

**Closed** 2020-01-22 21:13 UTC
