### ISSUE TITLE
Building gets flooded after rejoin!

### ISSUE THREAD

**Issue by damien1406** [SubnauticaNitrox/Nitrox#1420] opened 2021-02-09 16:40 UTC
Latest Version!!!

How can we fix this?

RESPOND ASAP! THIS IS GETTING REALLY ANNOYING!

**Comment by Coding-Hen** [comment] 2021-02-09 16:45
Im closing this as you are not following the template for issues and dont give us any information about actually what the issue is, how it can be replicated or useful information. Im going to assime that you mean when you are in a base and spawn in you are swimming till you go out a hatch and it brings you back rather than the base having leaks and actually being flooded?

**Closed by Coding-Hen** 2021-02-09 16:45 UTC
