### ISSUE TITLE
Every 15 seconds i freeze

### ISSUE THREAD

**Issue by Oryx84** [SubnauticaNitrox/Nitrox#1413] opened 2021-01-27 14:53 UTC

**Comment by Jannify** [comment] 2021-01-27 15:02
A few things to narrow down the issue would be neat. Like when does it happen, is it exactly 15 seconds or more or less random, on every machine or just one,  where is the server hosted, etc...
Just bear in mind we have limited time and can't reproduce bugs that are just happening one player...

**Comment by Oryx84** [comment] 2021-01-27 15:58
it just happens to me in any party

**Comment by Exso12Ecesis** [comment] 2021-01-27 22:59
This sounds like user error to me.

**Comment by Measurity** [comment] 2021-01-28 13:22
Closing because insufficient information to fix. We know Nitrox stutters when loading in new parts of the world due to the amount of data that is send across by server. Either provide more information on when exactly this happens (standing still, going to x, opening inventory, etc..) or wait for us to improve the performance.

**Closed by Measurity** 2021-01-28 13:22 UTC
