### ISSUE TITLE
inventory / wardrobe reset

### ISSUE THREAD

**Issue by franckysnoww** [SubnauticaNitrox/Nitrox#1136] opened 2020-06-11 17:39 UTC
Was working on a base from 2 day with " no problem " except floating transparent wall

But today after restarting the server, no more items in invetories / base, all other items like confinement / aquarium, etc.. are here but empty too.

**Comment by Measurity** [comment] 2020-06-11 20:49
Known issue. Duplicate of #1003

**Closed by Measurity** 2020-06-11 20:49 UTC
