### ISSUE TITLE
DELETE THIS

### ISSUE THREAD

**Issue by mikekmp** [SubnauticaNitrox/Nitrox#375] opened 2018-12-17 14:07 UTC

**Comment by Sajgoniarz** [comment] 2018-12-17 14:22
Duplicate https://github.com/SubnauticaNitrox/Nitrox/issues/352

**Comment by mikekmp** [comment] 2018-12-17 15:08
oops

**Comment by Hacksawfred3232** [comment] 2018-12-17 15:40
You can just put "[Duplicate of #352]" in the title and close it. @mikekmp

**Closed** 2018-12-17 18:14 UTC
