### ISSUE TITLE
Flood isolation with bulkheads sync

### ISSUE THREAD

**Issue by quimnuss** [SubnauticaNitrox/Nitrox#559] opened 2019-01-01 23:43 UTC
May be solved on its own if hull damage is synced. See #130

Bulkheads are supposed to isolate flooded areas. If the player repairs an area but not another isolated by a bulkhead, the other players don't see it flooded.

However, maybe because hull cracks are not synced as per the other issue, fixing that one might fix this one.

**Comment by Jannify** [comment] 2021-05-09 15:34
Now a duplicate of #130

**Closed by Jannify** 2021-05-09 15:34 UTC
