### ISSUE TITLE
Stuck on Title Screen when launching from Nitrox Multiplayer

### ISSUE THREAD

**Issue by BenjaminWatson1606** [SubnauticaNitrox/Nitrox#1510] opened 2021-07-05 14:32 UTC
### Steps to reproduce || Launch game from Nitrox on Multiplayer

I've tried multiple ways to attempt to fix this like redownloading the whole game, verifying the integrity of Steam Files, updating drivers etc.. But none of them seem to work, if someone has a fix, plz help. Thx

**Comment by TheLxkas** [comment] 2021-07-05 14:33
If you need help I recommend asking on our support discord. It's a lot easier that way.
https://discord.gg/E8B4X9s

**Comment by Jannify** [comment] 2021-07-05 14:35
This is a common issue if the installation is not correct, therefor this is probably not a bug. Closing it.

**Closed by Jannify** 2021-07-05 14:35 UTC

**Comment by BenjaminWatson1606** [comment] 2021-07-05 14:40
> This is a common issue if the installation is not correct, therefor this is probably not a bug. Closing it.

Yeah but how exactly am I supposed to fix it ?

**Comment by TheLxkas** [comment] 2021-07-05 14:41
as I wrote before, I'm happy to help you on our discord server

**Comment by BenjaminWatson1606** [comment] 2021-07-05 14:43
> as I wrote before, I'm happy to help you on our discord server

Yeah but I have to wait a bit to be able to send a message apparently, don't have authorization
