### ISSUE TITLE
game won't open.

### ISSUE THREAD

**Issue by Kodi4444** [SubnauticaNitrox/Nitrox#862] opened 2019-12-14 06:14 UTC
this is the error I get when I click the play multiplayer button and I made sure the path is correct.
![image](https://user-images.githubusercontent.com/26844364/70844425-2782be80-1dfe-11ea-8e55-a9c523eb1545.png)
I think it's related to the infinite loading bug previously submitted. because after reinstalling Subnautica the game will load but it won't launch from the nitrox launcher.

**Comment by Coding-Hen** [comment] 2019-12-14 10:22
This is due to the subnautica update moving folders around the mono folder has moved hence it couldnt find it. For now if on steam downgrade to the working version as described on the discord help channel pinned messages, should do the fix.

**Comment by Kodi4444** [comment] 2019-12-14 22:27
im on epic, not steam. 
will this be fixed soon?

**Comment by Coding-Hen** [comment] 2019-12-14 22:31
It will in the next release

**Comment by KingTyl3r** [comment] 2019-12-15 05:00
any known date of the next update

**Comment by Coding-Hen** [comment] 2020-01-04 15:39
@Measurity This can also be closed fixed as mentioned with merge

**Comment by Measurity** [comment] 2020-01-04 19:23
I'll leave it open for a while until a new release is on nexusmods.

**Comment by Measurity** [comment] 2020-01-09 23:43
Duplicate of #856

**Closed by Measurity** 2020-01-09 23:43 UTC
