### ISSUE TITLE
Some entities standing still

### ISSUE THREAD

**Issue by ghost** [SubnauticaNitrox/Nitrox#1600] opened 2021-09-17 15:38 UTC
### Version

Alpha 1.5.0.1

### Issue
Some fishes standing still

There is a problem with some fishes (the most noticeable being the bleeder) that causes them to sit still and not attack, with some friendly fishes you have to stay near them for about 10-20 seconds for them to start moving     
UPDATE: this also happens to Warper and some Crabsnake

### Extra info
[LOGFILE](https://cdn.lucaservers.com/SUB/09-17.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-17-prev.log)
[SCREENSHOT Warper](https://cdn.lucaservers.com/SUB/2021-09-17_00012.jpg)
[SCREENSHOT Bleeder](https://cdn.lucaservers.com/SUB/2021-09-17_00002.jpg)
[SCREENSHOT Crabsnake](https://cdn.lucaservers.com/SUB/2021-09-17_00013.jpg)

**Comment by xSimone** [comment] 2022-03-22 12:45
Confirm for Bleeder, Warper and Crabsnake

**Comment by Jannify** [comment] 2024-01-09 02:04
Duplicate of #113

**Closed by Jannify** 2024-01-09 02:04 UTC
Labels: Type: bug, Area: netcode
