### ISSUE TITLE
Seamoth gets stuck on nothing.

### ISSUE THREAD

**Issue by lazackna** [SubnauticaNitrox/Nitrox#1522] opened 2021-07-11 08:49 UTC
### Version

1.4.0.0

### Bug

Sometimes the seamoth gets stuck while playing on a server.

### Expected

You just play the game and the seamoth gets stuck all of a sudden.

### Steps to reproduce

Just explore with the seamoth. After a random amount of time it will get stuck on nothing.

### Other details:

It can be fixed by leaving the server while in the seamoth and rejoining. This puts you next to the seamoth. But this fix is a gamble. When rejoining you will loose oxygen. Depending on how deep you are you might die.

**Comment by TheLxkas** [comment] 2021-07-11 08:51
you can also fix this by making another player drive it.
And yes this is already known.

**Comment by Measurity** [comment] 2021-07-11 08:53
Can you still slightly look around with seamoth when it is stuck? This could tell us something about the cause.

**Comment by lazackna** [comment] 2021-07-11 22:19
Won't budge even a bit. It will become completely stuck.

**Comment by Droow** [comment] 2021-08-30 22:43
For me, it can slightly move to the sides using the mouse but will immediately return to its stuck position. And yes, it can be fixed by another player driving it, but then the seamoth upgrades sometimes disappear for one of the players.

**Closed** 2022-02-03 16:28 UTC
Labels: Type: bug, Status: verified, Area: vehicles
