### ISSUE TITLE
Fragments in ship wrecks not spawning

### ISSUE THREAD

**Issue by LagySpagyCZ** [SubnauticaNitrox/Nitrox#1776] opened 2022-04-08 14:35 UTC
### Version
1.6.0.0

### Bug
In ship wrecks there are no fragments like nuclear reactor, prawn upgrades, modification station and more

### Expected
Fragments to spawn

### Other details:
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/8452754/Player.log)
[Player-prev.log](https://github.com/SubnauticaNitrox/Nitrox/files/8452756/Player-prev.log)

**Comment by AdrienMau** [comment] 2022-04-10 14:14
Not sure how much of a bug it is. Spawns seem to be random. See: https://steamcommunity.com/app/264710/discussions/0/1489987634020237530/

To be sure of it being a bug, we would need to be able to know that they really did not spawn anywhere.

**Comment by LagySpagyCZ** [comment] 2022-04-10 16:28
Emm Maybe i can send some screenshots and if that is not gonna be enough then you can see throuh teamviewer or someting different.

**Comment by Chr0n4s** [comment] 2022-04-29 17:37
Can confirm this. Not even one wreck got any interior.

**Comment by Alvetore** [comment] 2022-05-01 13:59
No doors, no interior, no fragment in ship wrecks.

**Comment by LagySpagyCZ** [comment] 2022-05-01 14:04
Like in interiors of ship wrecks and outside too. In locked doors that you need to cut but in the Aurora there is the main loot. If you want to help me send me a request on discord. LagySpagyCZ#7084

**Comment by Jannify** [comment] 2022-05-25 17:13
Duplicate of #1779

**Closed by Jannify** 2022-05-25 17:13 UTC
Labels: Type: bug
