### ISSUE TITLE
Random floating blueprints when rejoining

### ISSUE THREAD

**Issue by RedSpid3r** [SubnauticaNitrox/Nitrox#1128] opened 2020-06-06 02:29 UTC
When rejoining a game, there will often be random floating blueprints that you cannot build or deconstruct, but also they prevent you from deconstructing any attached or placed buildings in close proximity.

![image](https://user-images.githubusercontent.com/12657277/83934054-b23ce880-a7a5-11ea-849b-4605eae74819.png)

![image](https://user-images.githubusercontent.com/12657277/83934101-fe882880-a7a5-11ea-8e70-d3595693805e.png)

**Comment by Damouchka** [comment] 2020-08-09 06:43
is there no command to correct that?

**Comment by TheClockTwister** [comment] 2020-12-18 02:10
## Cause & Status
This is related to the construction problems described in [Issue 691](https://github.com/SubnauticaNitrox/Nitrox/issues/691) and maby even [Issue 951](https://github.com/SubnauticaNitrox/Nitrox/issues/951).
Since the construction system is quite complex due to sync activity, we will need more time to get this to near perfection...

## Workaround
Meanwhile, if you are using [version 1.4.0](https://github.com/SubnauticaNitrox/Nitrox/releases/tag/1.4.0.0) or later, you can set the serialization type to JSON in your server config:

Contents of `server.cfg`:
```
...
SerializerMode=JSON
...
```
This allows you to run very simple scripts on the server-side data once the world is saved. For exampel, using this script, you can finish all unfinished constructions in the current world (**_NOTE: this method is more a last-resort solution rather than a permanent fix_**):
```python
import json

with open('BaseData.json', 'r') as f:
    data = json.load(f)

print('completed items before patch:', len(data['CompletedBasePieceHistory']))

for incomplete_item in data['PartiallyConstructedPieces']:
    incomplete_item['ConstructionAmount'] = 1.0
    incomplete_item['ConstructionCompleted'] = True
    data['CompletedBasePieceHistory'].append(incomplete_item)

data['PartiallyConstructedPieces'] = []

print('completed items after patch :', len(data['CompletedBasePieceHistory']))

with open('BaseData.json', 'w') as f:
    json.dump(data, f)

```

**Comment by EinLuigi** [comment] 2020-12-30 19:29
in which file this script?

**Comment by Coding-Hen** [comment] 2020-12-30 19:31
@EinLuigi This is a Python script, it needs to be run outside on Nitrox in the save folder

**Comment by EinLuigi** [comment] 2020-12-30 19:34
is it possible to convert the existing .nitrox files to .json?

**Comment by Coding-Hen** [comment] 2020-12-31 19:33
No this is not possible, a new file save will be created upon change of serialisation type

**Comment by EinLuigi** [comment] 2021-01-02 17:31
but than all my items are gone

**Comment by Measurity** [comment] 2021-01-02 17:32
You can get them back with cheats: https://subnautica.fandom.com/wiki/Console_Commands

**Comment by romgerman** [comment] 2021-01-24 11:59
Can confirm. This is super annoying
![2021-01-24_00001](https://user-images.githubusercontent.com/1517367/105629529-941b1a00-5e54-11eb-8d44-2070fc5a7bf7.jpg)
And this is a water purifier
![2021-01-24_00002](https://user-images.githubusercontent.com/1517367/105629537-a5642680-5e54-11eb-96ad-f0f2c32a2439.jpg)
Which should be here (you can see the bubbles)
![2021-01-24_00003](https://user-images.githubusercontent.com/1517367/105629555-b9a82380-5e54-11eb-9f28-9f38e8505d2b.jpg)
And i can't use that and can't remove that.

**Comment by Jannify** [comment] 2021-05-09 16:08
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/1400

**Closed by Jannify** 2021-05-09 16:08 UTC
Labels: Type: bug, duplicate
