### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by XL3GEND** [SubnauticaNitrox/Nitrox#577] opened 2019-01-05 14:11 UTC
Disappearing plants, such as acid mushrooms or corals, in the once visited areas.
Kamikaze fish cant get out of it's nest and warpers doesn't react.
+Mushrooms in the rescue capsule storage disappear.
+My friend flies away and turns on himself to infinity, coming back every time (it does not always happen)
+This message is always spamming the logs "[Nitrox] I: Could not update entity position because it was not found (maybe it was recently picked up)"
+Some fish doesn't move and are black. > The Shuttlebug has the animation to move but do not move (but is not black)
+When you put a bottle of oxygen for the first time, the oxygen is unlimited and you have to remove it and put it back in the water to correct

**Comment by XL3GEND** [comment] 2019-01-05 14:14
+This message is always spamming the logs "[Nitrox] I: Could not update entity position because it was not found (maybe it was recently picked up)"

**Comment by GW-GhostWolf** [comment] 2019-01-06 22:07
Oxygen - duplicate of issue #290

**Closed** 2020-05-10 20:35 UTC
