### ISSUE TITLE
Subnautica Error

### ISSUE THREAD

**Issue by AshKetchup6** [SubnauticaNitrox/Nitrox#1163] opened 2020-07-10 00:49 UTC
Ok, so, this randomly started happening today and I am confused as to why, whenever I start up my subnautica server it comes up with an error message that lasts a second then disappears, in the youtube video attached I slowed down the footage of the code so you experts can help me find what is bugging it. When watching the video it's still pretty fast so just pause the video when it shows the error code
[Error Video](https://youtu.be/S5OzZRZVT1Y)

**Comment by Coding-Hen** [comment] 2020-07-11 11:16
Duplicate of #1143

**Closed by Coding-Hen** 2020-07-11 11:16 UTC
