### ISSUE TITLE
When building the Nitrox project, an error occurs saying "The "DiscoverGame" task failed unexpectedly."

### ISSUE THREAD

**Issue by titan3755** [SubnauticaNitrox/Nitrox#2183] opened 2024-10-08 07:30 UTC
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

I cloned the github repo and loaded the "Nitrox.sln" file from Visual Studio and ran "dotnet restore". Up to this point, everything runs nicely but when I try to build the project (without any modifications to the code), the build process fails with a bunch of errors. The first of which is given below:

`The "DiscoverGame" task failed unexpectedly.`

Q. Do I need to have subnautica installed when building the project? 
Q. Do I need to have (steam) subnautica installed in the C drive?

If I don't need to have subnautica installed when building the project, how to I fix this problem?

**Comment by Measurity** [comment] 2024-10-08 09:38
> Q. Do I need to have Subnautica installed when building the project?

Yes, you do. Nitrox compiles against the game code, you need Subnautica installed for that. This is done to maintain a reasonable quality level of Nitrox code.

> Q. Do I need to have (steam) Subnautica installed in the C drive?

No, it should work regardless. If not, please create a new issue with the error message from the `DiscoverGame` task.

___
Closing this issue as it is by design. If there are other unexpected problems let us know by creating a new issue on GitHub.

**Closed by Measurity** 2024-10-08 09:38 UTC
Labels: Type: bug, Status: to verify

**Comment by RedStylzZ** [comment] 2024-10-16 20:26
I had the same problem I think. For me it was the problem that the config said Subnautica is installed at C: but for me it was on F:
I moved it then to C: and then it worked fine
