### ISSUE TITLE
Flying blueprints

### ISSUE THREAD

**Issue by Etound** [SubnauticaNitrox/Nitrox#1328] opened 2020-12-19 18:36 UTC
### Version
Alpha 1.4.0.0 

### Bug
 flying hatch or door schematic appears  https://user-images.githubusercontent.com/76262344/102696792-40a02580-4231-11eb-9947-07b1f826558c.png And i can't destroy that section

### Expected
It should never appear  

### Steps to reproduce
I don't really know i was just building

**Comment by EinLuigi** [comment] 2021-01-03 17:06
same problem

**Comment by Jannify** [comment] 2021-05-09 16:43
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/1400

**Closed by Jannify** 2021-05-09 16:43 UTC
